//! Unprivileged opaque relay spool and hosted projection safety model.
//!
//! The relay can persist, duplicate, delay and route envelopes. It cannot
//! inspect an envelope as authorization, mutate broker state, or decide that a
//! service acknowledgement means package execution occurred.

#![forbid(unsafe_code)]

use std::collections::BTreeMap;
use thiserror::Error;

pub const MAX_OPAQUE_ENVELOPE_BYTES: usize = 262_144;

/// Exactly 16 routing bytes, generated by the producer and independent from a
/// broker request or receipt identifier.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct EnvelopeId([u8; 16]);

impl EnvelopeId {
    #[must_use]
    pub const fn new(value: [u8; 16]) -> Self {
        Self(value)
    }

    #[must_use]
    pub const fn as_bytes(self) -> [u8; 16] {
        self.0
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Direction {
    BrokerToService,
    ServiceToBroker,
}

/// Opaque signed-object routing class. It intentionally conveys no authority.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ObjectKind {
    EnrollmentAcknowledgement,
    Request,
    LifecycleEvent,
    Receipt,
    KeysetAcknowledgement,
    ServiceKeyset,
    DecisionSubmission,
    RevocationEvent,
    ResyncRequest,
}

impl ObjectKind {
    #[must_use]
    pub const fn permitted_in(self, direction: Direction) -> bool {
        matches!(
            (self, direction),
            (Self::EnrollmentAcknowledgement, Direction::BrokerToService)
                | (Self::Request, Direction::BrokerToService)
                | (Self::LifecycleEvent, Direction::BrokerToService)
                | (Self::Receipt, Direction::BrokerToService)
                | (Self::KeysetAcknowledgement, Direction::BrokerToService)
                | (Self::ServiceKeyset, Direction::ServiceToBroker)
                | (Self::DecisionSubmission, Direction::ServiceToBroker)
                | (Self::RevocationEvent, Direction::ServiceToBroker)
                | (Self::ResyncRequest, Direction::ServiceToBroker)
        )
    }
}

/// Bytes received from a broker mailbox or service mailbox. `payload` is never
/// parsed by this crate; verification belongs to the receiving authority.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct OpaqueEnvelope {
    pub envelope_id: EnvelopeId,
    pub direction: Direction,
    pub kind: ObjectKind,
    pub idempotency_key: [u8; 32],
    pub payload: Vec<u8>,
}

impl OpaqueEnvelope {
    pub fn new(
        envelope_id: EnvelopeId,
        direction: Direction,
        kind: ObjectKind,
        idempotency_key: [u8; 32],
        payload: Vec<u8>,
    ) -> Result<Self, RelayError> {
        if !kind.permitted_in(direction) {
            return Err(RelayError::InvalidDirection);
        }
        if payload.len() > MAX_OPAQUE_ENVELOPE_BYTES {
            return Err(RelayError::PayloadTooLarge);
        }
        Ok(Self { envelope_id, direction, kind, idempotency_key, payload })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DeliveryAttempt {
    pub envelope: OpaqueEnvelope,
    pub attempts: u32,
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct SpoolEntry {
    envelope: OpaqueEnvelope,
    attempts: u32,
    next_attempt_mono_ns: u64,
}

/// Durable-spool model. A real persistence adapter must write the envelope
/// before returning from `enqueue` and delete it only after `acknowledge`.
#[derive(Debug, Default)]
pub struct RelaySpool {
    entries: BTreeMap<EnvelopeId, SpoolEntry>,
}

impl RelaySpool {
    pub fn enqueue(&mut self, envelope: OpaqueEnvelope, now_mono_ns: u64) -> Result<(), RelayError> {
        if self.entries.contains_key(&envelope.envelope_id) {
            return Err(RelayError::DuplicateEnvelopeId);
        }
        self.entries.insert(envelope.envelope_id, SpoolEntry { envelope, attempts: 0, next_attempt_mono_ns: now_mono_ns });
        Ok(())
    }

    /// Claims one ready envelope while retaining it durably for at-least-once
    /// delivery. Calling this again without an acknowledgement may redeliver it.
    pub fn next_delivery(&mut self, now_mono_ns: u64) -> Option<DeliveryAttempt> {
        let (_, entry) = self.entries.iter_mut().find(|(_, entry)| entry.next_attempt_mono_ns <= now_mono_ns)?;
        entry.attempts = entry.attempts.saturating_add(1);
        Some(DeliveryAttempt { envelope: entry.envelope.clone(), attempts: entry.attempts })
    }

    /// Authenticated acknowledgement removes exactly the matching retained
    /// object. A mismatched idempotency key must not delete a spool record.
    pub fn acknowledge(&mut self, envelope_id: EnvelopeId, idempotency_key: [u8; 32]) -> Result<(), RelayError> {
        let entry = self.entries.get(&envelope_id).ok_or(RelayError::UnknownEnvelope)?;
        if entry.envelope.idempotency_key != idempotency_key {
            return Err(RelayError::AcknowledgementMismatch);
        }
        self.entries.remove(&envelope_id);
        Ok(())
    }

    /// Leaves the envelope in the spool and schedules a bounded retry time.
    pub fn retry_later(&mut self, envelope_id: EnvelopeId, next_attempt_mono_ns: u64) -> Result<(), RelayError> {
        let entry = self.entries.get_mut(&envelope_id).ok_or(RelayError::UnknownEnvelope)?;
        entry.next_attempt_mono_ns = next_attempt_mono_ns;
        Ok(())
    }

    #[must_use]
    pub fn len(&self) -> usize {
        self.entries.len()
    }

    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }
}

#[derive(Debug, Error, Clone, PartialEq, Eq)]
pub enum RelayError {
    #[error("object kind is not valid for this relay direction")]
    InvalidDirection,
    #[error("opaque envelope exceeds the relay byte limit")]
    PayloadTooLarge,
    #[error("envelope ID is already retained in the spool")]
    DuplicateEnvelopeId,
    #[error("envelope is not retained in the spool")]
    UnknownEnvelope,
    #[error("acknowledgement does not match the retained idempotency key")]
    AcknowledgementMismatch,
    #[error("event sequence cannot be applied contiguously")]
    SequenceGap,
}

/// Verified lifecycle metadata supplied by the service verifier after it has
/// checked the broker signature. The relay itself must not construct this from
/// an opaque payload.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct VerifiedLifecycleEvent {
    pub sequence: u64,
    pub event_digest: [u8; 32],
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ProjectionResult {
    Applied,
    Duplicate,
    FrozenGap,
}

/// Hosted projection guard for at-least-once, out-of-order relay delivery.
/// It does not pick an authoritative lifecycle state; it only records verified
/// contiguous event identities and freezes on ambiguity.
#[derive(Debug, Default)]
pub struct ProjectionChain {
    applied: BTreeMap<u64, [u8; 32]>,
    next_sequence: u64,
    frozen_gap: bool,
}

impl ProjectionChain {
    #[must_use]
    pub fn is_frozen(&self) -> bool {
        self.frozen_gap
    }

    #[must_use]
    pub fn next_sequence(&self) -> u64 {
        if self.next_sequence == 0 { 1 } else { self.next_sequence }
    }

    pub fn ingest(&mut self, event: VerifiedLifecycleEvent) -> ProjectionResult {
        if self.frozen_gap {
            return ProjectionResult::FrozenGap;
        }
        let expected = self.next_sequence();
        if event.sequence == expected {
            self.applied.insert(event.sequence, event.event_digest);
            self.next_sequence = expected.saturating_add(1);
            return ProjectionResult::Applied;
        }
        if event.sequence < expected && self.applied.get(&event.sequence) == Some(&event.event_digest) {
            return ProjectionResult::Duplicate;
        }
        self.frozen_gap = true;
        ProjectionResult::FrozenGap
    }

    /// Replaces a frozen projection only with an independently verified, exact
    /// sequence beginning at one. Any duplicate digest conflict or gap remains
    /// frozen and triggers another resync request at the caller.
    pub fn restore_contiguous(&mut self, events: impl IntoIterator<Item = VerifiedLifecycleEvent>) -> Result<(), RelayError> {
        let mut candidate = Self::default();
        for event in events {
            if candidate.ingest(event) != ProjectionResult::Applied {
                return Err(RelayError::SequenceGap);
            }
        }
        *self = candidate;
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn envelope(id: u8) -> OpaqueEnvelope {
        OpaqueEnvelope::new(
            EnvelopeId::new([id; 16]),
            Direction::BrokerToService,
            ObjectKind::LifecycleEvent,
            [id; 32],
            vec![id],
        )
        .unwrap()
    }

    fn event(sequence: u64, digest: u8) -> VerifiedLifecycleEvent {
        VerifiedLifecycleEvent { sequence, event_digest: [digest; 32] }
    }

    #[test]
    fn spool_retains_until_matching_acknowledgement_and_allows_redelivery() {
        let mut spool = RelaySpool::default();
        let queued = envelope(1);
        spool.enqueue(queued.clone(), 10).unwrap();
        assert_eq!(spool.next_delivery(9), None);
        assert_eq!(spool.next_delivery(10).unwrap().attempts, 1);
        assert_eq!(spool.next_delivery(10).unwrap().attempts, 2);
        assert_eq!(spool.acknowledge(queued.envelope_id, [2; 32]), Err(RelayError::AcknowledgementMismatch));
        assert_eq!(spool.len(), 1);
        spool.acknowledge(queued.envelope_id, [1; 32]).unwrap();
        assert!(spool.is_empty());
    }

    #[test]
    fn invalid_direction_and_oversize_payload_never_enter_the_spool() {
        assert_eq!(
            OpaqueEnvelope::new(EnvelopeId::new([1; 16]), Direction::ServiceToBroker, ObjectKind::Receipt, [1; 32], vec![]),
            Err(RelayError::InvalidDirection)
        );
        assert_eq!(
            OpaqueEnvelope::new(
                EnvelopeId::new([1; 16]), Direction::BrokerToService, ObjectKind::Receipt, [1; 32], vec![0; MAX_OPAQUE_ENVELOPE_BYTES + 1]
            ),
            Err(RelayError::PayloadTooLarge)
        );
    }

    #[test]
    fn projection_freezes_on_reorder_or_conflicting_duplicate_and_restores_only_contiguous_history() {
        let mut projection = ProjectionChain::default();
        assert_eq!(projection.ingest(event(1, 1)), ProjectionResult::Applied);
        assert_eq!(projection.ingest(event(1, 1)), ProjectionResult::Duplicate);
        assert_eq!(projection.ingest(event(3, 3)), ProjectionResult::FrozenGap);
        assert!(projection.is_frozen());
        assert_eq!(projection.ingest(event(2, 2)), ProjectionResult::FrozenGap);
        projection.restore_contiguous([event(1, 1), event(2, 2), event(3, 3)]).unwrap();
        assert!(!projection.is_frozen());
        assert_eq!(projection.next_sequence(), 4);
        assert_eq!(projection.ingest(event(2, 9)), ProjectionResult::FrozenGap);
    }
}
