//! Unprivileged opaque relay spool and hosted projection safety model.
//!
//! The relay can persist, duplicate, delay and route envelopes. It cannot
//! inspect an envelope as authorization, mutate broker state, or decide that a
//! service acknowledgement means package execution occurred.

#![forbid(unsafe_code)]
#![allow(clippy::missing_errors_doc)]

use std::collections::BTreeMap;
use std::fs;
use std::io::{Cursor, Read, Write};
use std::path::PathBuf;
use thiserror::Error;

pub const MAX_OPAQUE_ENVELOPE_BYTES: usize = 262_144;
pub const MAX_RETAINED_ENVELOPES: usize = 4_096;
const SPOOL_MAGIC: &[u8; 8] = b"RPSPOOL1";

/// Exactly 16 routing bytes, generated by the producer and independent from a
/// broker request or receipt identifier.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct EnvelopeId([u8; 16]);

impl EnvelopeId {
    #[must_use]
    pub const fn new(value: [u8; 16]) -> Self {
        Self(value)
    }

    #[must_use]
    pub const fn as_bytes(self) -> [u8; 16] {
        self.0
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Direction {
    BrokerToService,
    ServiceToBroker,
}

/// Opaque signed-object routing class. It intentionally conveys no authority.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ObjectKind {
    EnrollmentAcknowledgement,
    Request,
    LifecycleEvent,
    Receipt,
    KeysetAcknowledgement,
    ServiceKeyset,
    DecisionSubmission,
    RevocationEvent,
    ResyncRequest,
}

impl ObjectKind {
    #[must_use]
    pub const fn permitted_in(self, direction: Direction) -> bool {
        matches!(
            (self, direction),
            (
                Self::EnrollmentAcknowledgement
                    | Self::Request
                    | Self::LifecycleEvent
                    | Self::Receipt
                    | Self::KeysetAcknowledgement,
                Direction::BrokerToService
            ) | (
                Self::ServiceKeyset
                    | Self::DecisionSubmission
                    | Self::RevocationEvent
                    | Self::ResyncRequest,
                Direction::ServiceToBroker
            )
        )
    }
}

/// Bytes received from a broker mailbox or service mailbox. `payload` is never
/// parsed by this crate; verification belongs to the receiving authority.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct OpaqueEnvelope {
    pub envelope_id: EnvelopeId,
    pub direction: Direction,
    pub kind: ObjectKind,
    pub idempotency_key: [u8; 32],
    pub payload: Vec<u8>,
}

impl OpaqueEnvelope {
    pub fn new(
        envelope_id: EnvelopeId,
        direction: Direction,
        kind: ObjectKind,
        idempotency_key: [u8; 32],
        payload: Vec<u8>,
    ) -> Result<Self, RelayError> {
        if !kind.permitted_in(direction) {
            return Err(RelayError::InvalidDirection);
        }
        if payload.len() > MAX_OPAQUE_ENVELOPE_BYTES {
            return Err(RelayError::PayloadTooLarge);
        }
        Ok(Self {
            envelope_id,
            direction,
            kind,
            idempotency_key,
            payload,
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DeliveryAttempt {
    pub envelope: OpaqueEnvelope,
    pub attempts: u32,
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct SpoolEntry {
    envelope: OpaqueEnvelope,
    attempts: u32,
    next_attempt_mono_ns: u64,
}

/// Durable-spool model. A real persistence adapter must write the envelope
/// before returning from `enqueue` and delete it only after `acknowledge`.
#[derive(Debug, Clone, Default)]
pub struct RelaySpool {
    entries: BTreeMap<EnvelopeId, SpoolEntry>,
}

impl RelaySpool {
    pub fn enqueue(
        &mut self,
        envelope: OpaqueEnvelope,
        now_mono_ns: u64,
    ) -> Result<(), RelayError> {
        if self.entries.contains_key(&envelope.envelope_id) {
            return Err(RelayError::DuplicateEnvelopeId);
        }
        if self.entries.len() >= MAX_RETAINED_ENVELOPES {
            return Err(RelayError::MailboxFull);
        }
        self.entries.insert(
            envelope.envelope_id,
            SpoolEntry {
                envelope,
                attempts: 0,
                next_attempt_mono_ns: now_mono_ns,
            },
        );
        Ok(())
    }

    /// Claims one ready envelope while retaining it durably for at-least-once
    /// delivery. Calling this again without an acknowledgement may redeliver it.
    pub fn next_delivery(&mut self, now_mono_ns: u64) -> Option<DeliveryAttempt> {
        let (_, entry) = self
            .entries
            .iter_mut()
            .find(|(_, entry)| entry.next_attempt_mono_ns <= now_mono_ns)?;
        entry.attempts = entry.attempts.saturating_add(1);
        Some(DeliveryAttempt {
            envelope: entry.envelope.clone(),
            attempts: entry.attempts,
        })
    }

    /// Authenticated acknowledgement removes exactly the matching retained
    /// object. A mismatched idempotency key must not delete a spool record.
    pub fn acknowledge(
        &mut self,
        envelope_id: EnvelopeId,
        idempotency_key: [u8; 32],
    ) -> Result<(), RelayError> {
        let entry = self
            .entries
            .get(&envelope_id)
            .ok_or(RelayError::UnknownEnvelope)?;
        if entry.envelope.idempotency_key != idempotency_key {
            return Err(RelayError::AcknowledgementMismatch);
        }
        self.entries.remove(&envelope_id);
        Ok(())
    }

    /// Leaves the envelope in the spool and schedules a bounded retry time.
    pub fn retry_later(
        &mut self,
        envelope_id: EnvelopeId,
        next_attempt_mono_ns: u64,
    ) -> Result<(), RelayError> {
        let entry = self
            .entries
            .get_mut(&envelope_id)
            .ok_or(RelayError::UnknownEnvelope)?;
        entry.next_attempt_mono_ns = next_attempt_mono_ns;
        Ok(())
    }

    #[must_use]
    pub fn len(&self) -> usize {
        self.entries.len()
    }

    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }
}

/// A crash-safe, unprivileged local spool. It persists opaque envelope bytes
/// before reporting successful enqueue and atomically replaces the snapshot
/// after acknowledgement or retry scheduling. Receiving authorities still
/// verify every COSE object; this type has no signature or broker-key access.
#[derive(Debug)]
pub struct FileRelaySpool {
    path: PathBuf,
    spool: RelaySpool,
}

impl FileRelaySpool {
    /// Opens an existing spool or creates its durable parent on first write.
    pub fn open(path: impl Into<PathBuf>) -> Result<Self, RelayError> {
        let path = path.into();
        let spool = match fs::read(&path) {
            Ok(bytes) => decode_spool(&bytes)?,
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => RelaySpool::default(),
            Err(error) => return Err(RelayError::Storage(error.to_string())),
        };
        Ok(Self { path, spool })
    }

    /// Persists the envelope before returning success to the producer.
    pub fn enqueue(
        &mut self,
        envelope: OpaqueEnvelope,
        now_mono_ns: u64,
    ) -> Result<(), RelayError> {
        let mut candidate = self.spool.clone();
        candidate.enqueue(envelope, now_mono_ns)?;
        self.persist(&candidate)?;
        self.spool = candidate;
        Ok(())
    }

    /// Returns an at-least-once delivery attempt while retaining the envelope.
    #[must_use]
    pub fn next_delivery(&mut self, now_mono_ns: u64) -> Option<DeliveryAttempt> {
        self.spool.next_delivery(now_mono_ns)
    }

    /// Deletes only after the caller has authenticated a matching service ack.
    pub fn acknowledge(
        &mut self,
        envelope_id: EnvelopeId,
        idempotency_key: [u8; 32],
    ) -> Result<(), RelayError> {
        let mut candidate = self.spool.clone();
        candidate.acknowledge(envelope_id, idempotency_key)?;
        self.persist(&candidate)?;
        self.spool = candidate;
        Ok(())
    }

    /// Schedules a bounded exponential retry and persists the new deadline.
    pub fn retry_with_backoff(
        &mut self,
        envelope_id: EnvelopeId,
        now_mono_ns: u64,
    ) -> Result<u64, RelayError> {
        let mut candidate = self.spool.clone();
        let attempts = candidate
            .entries
            .get(&envelope_id)
            .ok_or(RelayError::UnknownEnvelope)?
            .attempts;
        let shift = attempts.min(16);
        let backoff_ns = 1_000_000_000_u64
            .saturating_mul(1_u64 << shift)
            .min(300_000_000_000);
        let next_attempt_mono_ns = now_mono_ns.saturating_add(backoff_ns);
        candidate.retry_later(envelope_id, next_attempt_mono_ns)?;
        self.persist(&candidate)?;
        self.spool = candidate;
        Ok(next_attempt_mono_ns)
    }

    #[must_use]
    pub fn len(&self) -> usize {
        self.spool.len()
    }

    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.spool.is_empty()
    }

    fn persist(&self, spool: &RelaySpool) -> Result<(), RelayError> {
        if let Some(parent) = self.path.parent() {
            fs::create_dir_all(parent).map_err(|error| RelayError::Storage(error.to_string()))?;
        }
        let temporary = self.path.with_extension("tmp");
        let mut file =
            fs::File::create(&temporary).map_err(|error| RelayError::Storage(error.to_string()))?;
        file.write_all(&encode_spool(spool))
            .map_err(|error| RelayError::Storage(error.to_string()))?;
        file.sync_all()
            .map_err(|error| RelayError::Storage(error.to_string()))?;
        fs::rename(temporary, &self.path)
            .map_err(|error| RelayError::Storage(error.to_string()))?;
        // A rename is not power-loss durable until its parent directory entry
        // is synced. Without this, enqueue/acknowledge could report success
        // while the old snapshot reappears after a crash.
        if let Some(parent) = self.path.parent() {
            fs::File::open(parent)
                .and_then(|directory| directory.sync_all())
                .map_err(|error| RelayError::Storage(error.to_string()))?;
        }
        Ok(())
    }
}

fn encode_spool(spool: &RelaySpool) -> Vec<u8> {
    let mut bytes = Vec::new();
    bytes.extend_from_slice(SPOOL_MAGIC);
    bytes.extend_from_slice(
        &u32::try_from(spool.entries.len())
            .unwrap_or(u32::MAX)
            .to_be_bytes(),
    );
    for entry in spool.entries.values() {
        bytes.extend_from_slice(&entry.envelope.envelope_id.0);
        bytes.push(match entry.envelope.direction {
            Direction::BrokerToService => 1,
            Direction::ServiceToBroker => 2,
        });
        bytes.push(object_kind_code(entry.envelope.kind));
        bytes.extend_from_slice(&entry.envelope.idempotency_key);
        bytes.extend_from_slice(&entry.attempts.to_be_bytes());
        bytes.extend_from_slice(&entry.next_attempt_mono_ns.to_be_bytes());
        bytes.extend_from_slice(
            &u32::try_from(entry.envelope.payload.len())
                .unwrap_or(u32::MAX)
                .to_be_bytes(),
        );
        bytes.extend_from_slice(&entry.envelope.payload);
    }
    bytes
}

fn decode_spool(bytes: &[u8]) -> Result<RelaySpool, RelayError> {
    let mut input = Cursor::new(bytes);
    let mut magic = [0; 8];
    input
        .read_exact(&mut magic)
        .map_err(|_| RelayError::CorruptSpool)?;
    if &magic != SPOOL_MAGIC {
        return Err(RelayError::CorruptSpool);
    }
    let count = read_u32(&mut input)?;
    if usize::try_from(count).map_err(|_| RelayError::CorruptSpool)? > MAX_RETAINED_ENVELOPES {
        return Err(RelayError::CorruptSpool);
    }
    let mut spool = RelaySpool::default();
    for _ in 0..count {
        let mut envelope_id = [0; 16];
        input
            .read_exact(&mut envelope_id)
            .map_err(|_| RelayError::CorruptSpool)?;
        let direction = decode_direction(read_byte(&mut input)?)?;
        let kind = decode_object_kind(read_byte(&mut input)?)?;
        let mut idempotency_key = [0; 32];
        input
            .read_exact(&mut idempotency_key)
            .map_err(|_| RelayError::CorruptSpool)?;
        let attempts = read_u32(&mut input)?;
        let next_attempt_mono_ns = read_u64(&mut input)?;
        let payload_len =
            usize::try_from(read_u32(&mut input)?).map_err(|_| RelayError::CorruptSpool)?;
        if payload_len > MAX_OPAQUE_ENVELOPE_BYTES {
            return Err(RelayError::CorruptSpool);
        }
        let mut payload = vec![0; payload_len];
        input
            .read_exact(&mut payload)
            .map_err(|_| RelayError::CorruptSpool)?;
        let envelope = OpaqueEnvelope::new(
            EnvelopeId::new(envelope_id),
            direction,
            kind,
            idempotency_key,
            payload,
        )
        .map_err(|_| RelayError::CorruptSpool)?;
        if spool
            .entries
            .insert(
                envelope.envelope_id,
                SpoolEntry {
                    envelope,
                    attempts,
                    next_attempt_mono_ns,
                },
            )
            .is_some()
        {
            return Err(RelayError::CorruptSpool);
        }
    }
    if usize::try_from(input.position()).ok() != Some(bytes.len()) {
        return Err(RelayError::CorruptSpool);
    }
    Ok(spool)
}

fn object_kind_code(kind: ObjectKind) -> u8 {
    match kind {
        ObjectKind::EnrollmentAcknowledgement => 1,
        ObjectKind::Request => 2,
        ObjectKind::LifecycleEvent => 3,
        ObjectKind::Receipt => 4,
        ObjectKind::KeysetAcknowledgement => 5,
        ObjectKind::ServiceKeyset => 6,
        ObjectKind::DecisionSubmission => 7,
        ObjectKind::RevocationEvent => 8,
        ObjectKind::ResyncRequest => 9,
    }
}
fn decode_direction(value: u8) -> Result<Direction, RelayError> {
    match value {
        1 => Ok(Direction::BrokerToService),
        2 => Ok(Direction::ServiceToBroker),
        _ => Err(RelayError::CorruptSpool),
    }
}
fn decode_object_kind(value: u8) -> Result<ObjectKind, RelayError> {
    match value {
        1 => Ok(ObjectKind::EnrollmentAcknowledgement),
        2 => Ok(ObjectKind::Request),
        3 => Ok(ObjectKind::LifecycleEvent),
        4 => Ok(ObjectKind::Receipt),
        5 => Ok(ObjectKind::KeysetAcknowledgement),
        6 => Ok(ObjectKind::ServiceKeyset),
        7 => Ok(ObjectKind::DecisionSubmission),
        8 => Ok(ObjectKind::RevocationEvent),
        9 => Ok(ObjectKind::ResyncRequest),
        _ => Err(RelayError::CorruptSpool),
    }
}
fn read_byte(input: &mut Cursor<&[u8]>) -> Result<u8, RelayError> {
    let mut value = [0; 1];
    input
        .read_exact(&mut value)
        .map_err(|_| RelayError::CorruptSpool)?;
    Ok(value[0])
}
fn read_u32(input: &mut Cursor<&[u8]>) -> Result<u32, RelayError> {
    let mut value = [0; 4];
    input
        .read_exact(&mut value)
        .map_err(|_| RelayError::CorruptSpool)?;
    Ok(u32::from_be_bytes(value))
}
fn read_u64(input: &mut Cursor<&[u8]>) -> Result<u64, RelayError> {
    let mut value = [0; 8];
    input
        .read_exact(&mut value)
        .map_err(|_| RelayError::CorruptSpool)?;
    Ok(u64::from_be_bytes(value))
}

#[derive(Debug, Error, Clone, PartialEq, Eq)]
pub enum RelayError {
    #[error("object kind is not valid for this relay direction")]
    InvalidDirection,
    #[error("opaque envelope exceeds the relay byte limit")]
    PayloadTooLarge,
    #[error("envelope ID is already retained in the spool")]
    DuplicateEnvelopeId,
    #[error("envelope is not retained in the spool")]
    UnknownEnvelope,
    #[error("acknowledgement does not match the retained idempotency key")]
    AcknowledgementMismatch,
    #[error("event sequence cannot be applied contiguously")]
    SequenceGap,
    #[error("relay mailbox has reached its bounded capacity")]
    MailboxFull,
    #[error("relay spool could not be read safely")]
    CorruptSpool,
    #[error("relay spool storage failed: {0}")]
    Storage(String),
}

/// Verified lifecycle metadata supplied by the service verifier after it has
/// checked the broker signature. The relay itself must not construct this from
/// an opaque payload.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct VerifiedLifecycleEvent {
    pub sequence: u64,
    pub event_digest: [u8; 32],
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ProjectionResult {
    Applied,
    Duplicate,
    FrozenGap,
}

/// Hosted projection guard for at-least-once, out-of-order relay delivery.
/// It does not pick an authoritative lifecycle state; it only records verified
/// contiguous event identities and freezes on ambiguity.
#[derive(Debug, Default)]
pub struct ProjectionChain {
    applied: BTreeMap<u64, [u8; 32]>,
    next_sequence: u64,
    frozen_gap: bool,
}

impl ProjectionChain {
    #[must_use]
    pub fn is_frozen(&self) -> bool {
        self.frozen_gap
    }

    #[must_use]
    pub fn next_sequence(&self) -> u64 {
        if self.next_sequence == 0 {
            1
        } else {
            self.next_sequence
        }
    }

    pub fn ingest(&mut self, event: VerifiedLifecycleEvent) -> ProjectionResult {
        if self.frozen_gap {
            return ProjectionResult::FrozenGap;
        }
        let expected = self.next_sequence();
        if event.sequence == expected {
            self.applied.insert(event.sequence, event.event_digest);
            self.next_sequence = expected.saturating_add(1);
            return ProjectionResult::Applied;
        }
        if event.sequence < expected
            && self.applied.get(&event.sequence) == Some(&event.event_digest)
        {
            return ProjectionResult::Duplicate;
        }
        self.frozen_gap = true;
        ProjectionResult::FrozenGap
    }

    /// Replaces a frozen projection only with an independently verified, exact
    /// sequence beginning at one. Any duplicate digest conflict or gap remains
    /// frozen and triggers another resync request at the caller.
    pub fn restore_contiguous(
        &mut self,
        events: impl IntoIterator<Item = VerifiedLifecycleEvent>,
    ) -> Result<(), RelayError> {
        let mut candidate = Self::default();
        for event in events {
            if candidate.ingest(event) != ProjectionResult::Applied {
                return Err(RelayError::SequenceGap);
            }
        }
        *self = candidate;
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn envelope(id: u8) -> OpaqueEnvelope {
        OpaqueEnvelope::new(
            EnvelopeId::new([id; 16]),
            Direction::BrokerToService,
            ObjectKind::LifecycleEvent,
            [id; 32],
            vec![id],
        )
        .unwrap()
    }

    fn event(sequence: u64, digest: u8) -> VerifiedLifecycleEvent {
        VerifiedLifecycleEvent {
            sequence,
            event_digest: [digest; 32],
        }
    }

    #[test]
    fn spool_retains_until_matching_acknowledgement_and_allows_redelivery() {
        let mut spool = RelaySpool::default();
        let queued = envelope(1);
        spool.enqueue(queued.clone(), 10).unwrap();
        assert_eq!(spool.next_delivery(9), None);
        assert_eq!(spool.next_delivery(10).unwrap().attempts, 1);
        assert_eq!(spool.next_delivery(10).unwrap().attempts, 2);
        assert_eq!(
            spool.acknowledge(queued.envelope_id, [2; 32]),
            Err(RelayError::AcknowledgementMismatch)
        );
        assert_eq!(spool.len(), 1);
        spool.acknowledge(queued.envelope_id, [1; 32]).unwrap();
        assert!(spool.is_empty());
    }

    #[test]
    fn invalid_direction_and_oversize_payload_never_enter_the_spool() {
        assert_eq!(
            OpaqueEnvelope::new(
                EnvelopeId::new([1; 16]),
                Direction::ServiceToBroker,
                ObjectKind::Receipt,
                [1; 32],
                vec![]
            ),
            Err(RelayError::InvalidDirection)
        );
        assert_eq!(
            OpaqueEnvelope::new(
                EnvelopeId::new([1; 16]),
                Direction::BrokerToService,
                ObjectKind::Receipt,
                [1; 32],
                vec![0; MAX_OPAQUE_ENVELOPE_BYTES + 1]
            ),
            Err(RelayError::PayloadTooLarge)
        );
    }

    #[test]
    fn projection_freezes_on_reorder_or_conflicting_duplicate_and_restores_only_contiguous_history()
    {
        let mut projection = ProjectionChain::default();
        assert_eq!(projection.ingest(event(1, 1)), ProjectionResult::Applied);
        assert_eq!(projection.ingest(event(1, 1)), ProjectionResult::Duplicate);
        assert_eq!(projection.ingest(event(3, 3)), ProjectionResult::FrozenGap);
        assert!(projection.is_frozen());
        assert_eq!(projection.ingest(event(2, 2)), ProjectionResult::FrozenGap);
        projection
            .restore_contiguous([event(1, 1), event(2, 2), event(3, 3)])
            .unwrap();
        assert!(!projection.is_frozen());
        assert_eq!(projection.next_sequence(), 4);
        assert_eq!(projection.ingest(event(2, 9)), ProjectionResult::FrozenGap);
    }

    #[test]
    fn file_spool_survives_restart_and_requires_a_matching_acknowledgement() {
        let path = std::env::temp_dir()
            .join(format!("rootpermit-relay-{}", std::process::id()))
            .join("spool.bin");
        let mut spool = FileRelaySpool::open(&path).unwrap();
        let queued = envelope(7);
        spool.enqueue(queued.clone(), 10).unwrap();
        drop(spool);

        let mut reopened = FileRelaySpool::open(&path).unwrap();
        assert_eq!(reopened.len(), 1);
        assert_eq!(reopened.next_delivery(10).unwrap().envelope, queued);
        assert_eq!(
            reopened.acknowledge(EnvelopeId::new([7; 16]), [8; 32]),
            Err(RelayError::AcknowledgementMismatch)
        );
        reopened
            .acknowledge(EnvelopeId::new([7; 16]), [7; 32])
            .unwrap();
        drop(reopened);
        assert_eq!(FileRelaySpool::open(&path).unwrap().len(), 0);
        std::fs::remove_dir_all(path.parent().unwrap()).unwrap();
    }

    #[test]
    fn file_spool_rejects_corruption_and_caps_backoff() {
        let path = std::env::temp_dir()
            .join(format!("rootpermit-relay-corrupt-{}", std::process::id()))
            .join("spool.bin");
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(&path, b"not a relay spool").unwrap();
        assert!(matches!(
            FileRelaySpool::open(&path),
            Err(RelayError::CorruptSpool)
        ));
        std::fs::remove_dir_all(path.parent().unwrap()).unwrap();

        let capped_path = std::env::temp_dir()
            .join(format!("rootpermit-relay-backoff-{}", std::process::id()))
            .join("spool.bin");
        let mut capped = FileRelaySpool::open(&capped_path).unwrap();
        let queued = envelope(9);
        capped.enqueue(queued, 0).unwrap();
        for _ in 0..17 {
            let _ = capped.next_delivery(0);
        }
        assert_eq!(
            capped
                .retry_with_backoff(EnvelopeId::new([9; 16]), 0)
                .unwrap(),
            300_000_000_000
        );
        std::fs::remove_dir_all(capped_path.parent().unwrap()).unwrap();
    }
}
