[package]
name = "rp-broker-api"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
libc = "0.2.176"
rp-protocol = { path = "../rp-protocol", version = "0.1.0" }
thiserror = "2.0.12"
rp-peercred = { path = "../rp-peercred", version = "0.0.0" }

[lints]
workspace = true
