//! Root-only, SQLite-backed lifecycle authority for the first RootPermit slice.
//!
//! This crate deliberately accepts only a typed Debian binary package name. It
//! owns the request/idempotency state transaction, but it does not plan or
//! execute APT work yet; those responsibilities belong to later M2/M4 layers.

#![forbid(unsafe_code)]

use rusqlite::{
    Connection, OptionalExtension, Transaction, TransactionBehavior, params,
};
use sha2::{Digest as _, Sha256};
use std::collections::BTreeSet;
use thiserror::Error;

const LOCAL_DEVICE_ID: &str = "AAAAAAAAAAAAAAAAAAAAAA";
const ACTIVE_STATES: &str = "'planning', 'pending', 'approved', 'executing'";

/// A kernel-authenticated requester UID.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct RequesterUid(u32);

impl RequesterUid {
    /// Creates a requester UID from the value supplied by `SO_PEERCRED`.
    #[must_use]
    pub const fn from_peer_cred(uid: u32) -> Self {
        Self(uid)
    }

    /// Returns the numeric Linux UID for persistence only.
    #[must_use]
    pub const fn as_u32(self) -> u32 {
        self.0
    }
}

/// A public RootPermit identifier: exactly 16 random bytes in base64url form.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct PublicId(String);

impl PublicId {
    /// Parses a public request identifier without accepting paths or control characters.
    pub fn parse(value: impl Into<String>) -> Result<Self, IntakeError> {
        let value = value.into();
        if value.len() != 22 || !value.bytes().all(is_base64url) {
            return Err(IntakeError::InvalidPublicId);
        }
        Ok(Self(value))
    }

    /// Returns the database-safe opaque identifier.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

/// Caller-selected key used to make a single package request idempotent.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct OperationKey(String);

impl OperationKey {
    /// Parses a bounded opaque operation key; it is never a shell fragment.
    pub fn parse(value: impl Into<String>) -> Result<Self, IntakeError> {
        let value = value.into();
        if !(16..=128).contains(&value.len()) || !value.bytes().all(is_base64url) {
            return Err(IntakeError::InvalidOperationKey);
        }
        Ok(Self(value))
    }

    /// Returns the opaque key for an equality-only database comparison.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

/// The only v1 agent-controlled operation input.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct PackageName(String);

impl PackageName {
    /// Parses a base Debian binary package name, excluding architecture, version and flags.
    pub fn parse(value: impl Into<String>) -> Result<Self, IntakeError> {
        let value = value.into();
        let bytes = value.as_bytes();
        if !(2..=64).contains(&bytes.len())
            || !bytes.first().is_some_and(u8::is_ascii_lowercase)
            || !bytes[1..].iter().copied().all(is_package_character)
        {
            return Err(IntakeError::InvalidPackageName);
        }
        Ok(Self(value))
    }

    /// Returns the validated package name.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

/// Errors raised before an agent request can influence broker state.
#[derive(Debug, Error, Clone, PartialEq, Eq)]
pub enum IntakeError {
    /// The request ID is not a 16-byte base64url identifier.
    #[error("request id must be a 16-byte base64url value")]
    InvalidPublicId,
    /// The caller did not supply a bounded opaque idempotency key.
    #[error("operation key must be a 16-128 character base64url value")]
    InvalidOperationKey,
    /// The package name is not a bounded, native Debian binary package name.
    #[error("package name must be 2-64 lowercase ASCII Debian-name characters")]
    InvalidPackageName,
}

/// A complete typed input to `package.install`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SubmitPackageInstall {
    /// Fresh public request ID generated by the broker, not the agent.
    pub request_id: PublicId,
    /// Caller identity supplied from `SO_PEERCRED`.
    pub requester_uid: RequesterUid,
    /// Caller retry key.
    pub operation_key: OperationKey,
    /// The sole agent-controlled operation value.
    pub package_name: PackageName,
    /// Credential generation captured when the request begins.
    pub generation: u64,
}

/// Policy decision for the one v1 operation type.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PolicyDecision {
    /// The validated package may enter planning.
    Allow,
    /// The package must not create any local request record.
    Deny,
}

/// Root-controlled policy consulted before a request becomes durable.
pub trait PackageInstallPolicy {
    /// Evaluates the package against the locally configured policy.
    fn evaluate(&self, requester_uid: RequesterUid, package_name: &PackageName) -> PolicyDecision;
}

/// Explicit package allowlist policy used by the local broker skeleton and tests.
#[derive(Debug, Clone, Default)]
pub struct PackageAllowlist {
    packages: BTreeSet<PackageName>,
}

impl PackageAllowlist {
    /// Builds an allowlist from already-validated package names.
    #[must_use]
    pub fn new(packages: impl IntoIterator<Item = PackageName>) -> Self {
        Self { packages: packages.into_iter().collect() }
    }
}

impl PackageInstallPolicy for PackageAllowlist {
    fn evaluate(&self, _requester_uid: RequesterUid, package_name: &PackageName) -> PolicyDecision {
        if self.packages.contains(package_name) {
            PolicyDecision::Allow
        } else {
            PolicyDecision::Deny
        }
    }
}

/// Authoritative lifecycle state retained in the broker database.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RequestState {
    /// A typed input has passed policy and awaits the planner.
    Planning,
    /// A frozen signed plan awaits a decision.
    Pending,
    /// A matching approval was accepted exactly once.
    Approved,
    /// The helper has received an execution authorization.
    Executing,
    /// Planning found no package transition.
    NoChange,
    /// Validation or planning rejected the request.
    Invalid,
    /// A matching deny assertion won the lifecycle race.
    Denied,
    /// The local monotonic deadline won the lifecycle race.
    Expired,
    /// The requester cancellation won before execution.
    Cancelled,
    /// The credential generation changed before execution.
    Stale,
    /// The helper proved the exact requested final state.
    Succeeded,
    /// The helper proved a failure without claiming rollback.
    Failed,
    /// A crash or ambiguity requires root reconciliation.
    RecoveryRequired,
}

impl RequestState {
    /// Returns whether this state closes the request and releases the active slot.
    #[must_use]
    pub const fn is_terminal(self) -> bool {
        matches!(
            self,
            Self::NoChange
                | Self::Invalid
                | Self::Denied
                | Self::Expired
                | Self::Cancelled
                | Self::Stale
                | Self::Succeeded
                | Self::Failed
        )
    }

    /// Returns whether a lifecycle edge is explicitly permitted by v2 section 5.2.
    #[must_use]
    pub const fn permits(self, next: Self) -> bool {
        matches!(
            (self, next),
            (Self::Planning, Self::Pending | Self::NoChange | Self::Invalid)
                | (Self::Pending, Self::Approved | Self::Denied | Self::Expired | Self::Cancelled | Self::Stale)
                | (Self::Approved, Self::Executing | Self::Cancelled | Self::Stale | Self::Expired)
                | (Self::Executing, Self::Succeeded | Self::Failed | Self::RecoveryRequired)
                | (Self::RecoveryRequired, Self::Succeeded | Self::Failed)
        )
    }

    const fn as_db(self) -> &'static str {
        match self {
            Self::Planning => "planning",
            Self::Pending => "pending",
            Self::Approved => "approved",
            Self::Executing => "executing",
            Self::NoChange => "no_change",
            Self::Invalid => "invalid",
            Self::Denied => "denied",
            Self::Expired => "expired",
            Self::Cancelled => "cancelled",
            Self::Stale => "stale",
            Self::Succeeded => "succeeded",
            Self::Failed => "failed",
            Self::RecoveryRequired => "recovery_required",
        }
    }

    fn from_db(value: &str) -> Result<Self, BrokerError> {
        match value {
            "planning" => Ok(Self::Planning),
            "pending" => Ok(Self::Pending),
            "approved" => Ok(Self::Approved),
            "executing" => Ok(Self::Executing),
            "no_change" => Ok(Self::NoChange),
            "invalid" => Ok(Self::Invalid),
            "denied" => Ok(Self::Denied),
            "expired" => Ok(Self::Expired),
            "cancelled" => Ok(Self::Cancelled),
            "stale" => Ok(Self::Stale),
            "succeeded" => Ok(Self::Succeeded),
            "failed" => Ok(Self::Failed),
            "recovery_required" => Ok(Self::RecoveryRequired),
            _ => Err(BrokerError::CorruptState),
        }
    }
}

/// A caller-safe projection of a local request.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RequestSummary {
    /// Opaque request ID.
    pub request_id: PublicId,
    /// Requester that owns the idempotency relationship.
    pub requester_uid: RequesterUid,
    /// Current durable lifecycle state.
    pub state: RequestState,
    /// The frozen credential generation boundary.
    pub generation: u64,
}

/// Result of a typed submission.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SubmitOutcome {
    /// A new request entered `planning`.
    Created(RequestSummary),
    /// The exact `(uid, operation key, input)` retry recovered its original request.
    Existing(RequestSummary),
}

/// Stable broker failures for lifecycle/state authority.
#[derive(Debug, Error)]
pub enum BrokerError {
    /// SQLite rejected or could not persist a state transition.
    #[error(transparent)]
    Sqlite(#[from] rusqlite::Error),
    /// The package policy rejected the request before any durable state was created.
    #[error("package install is not allowed by local policy")]
    PolicyDenied,
    /// The operation key was reused by one UID with different typed input.
    #[error("operation key was reused with different input")]
    IdempotencyConflict,
    /// A non-terminal request already consumes the one active device slot.
    #[error("a request is already active on this device: {request_id}")]
    Busy {
        /// Opaque request ID that owns the active slot.
        request_id: String,
    },
    /// The caller expected a state that did not win the compare-and-set race.
    #[error("lifecycle compare-and-set lost; current state is {actual:?}")]
    LifecycleRaceLost {
        /// The state observed after the failed CAS.
        actual: RequestState,
    },
    /// The requested edge is not in the v1 lifecycle graph.
    #[error("lifecycle transition from {from:?} to {to:?} is not permitted")]
    InvalidTransition {
        /// Expected source state.
        from: RequestState,
        /// Requested destination state.
        to: RequestState,
    },
    /// No local request exists for the opaque ID.
    #[error("request does not exist")]
    NotFound,
    /// Database data violates a broker-owned invariant.
    #[error("broker database contains an invalid lifecycle value")]
    CorruptState,
    /// SQLite stored an integer that does not fit its security-relevant type.
    #[error("broker database contains an out-of-range numeric value")]
    NumericOutOfRange,
}

/// Authoritative local state store; no other component may mutate its connection.
pub struct BrokerStore {
    connection: Connection,
    device_id: &'static str,
}

impl BrokerStore {
    /// Creates an in-memory store for deterministic lifecycle tests.
    pub fn in_memory() -> Result<Self, BrokerError> {
        let connection = Connection::open_in_memory()?;
        Self::from_connection(connection)
    }

    /// Installs broker-owned schema and pragmas on an otherwise private connection.
    pub fn from_connection(connection: Connection) -> Result<Self, BrokerError> {
        connection.execute_batch(&format!(
            "
            PRAGMA foreign_keys = ON;
            PRAGMA journal_mode = WAL;
            PRAGMA synchronous = FULL;
            CREATE TABLE IF NOT EXISTS requests (
                request_id TEXT PRIMARY KEY,
                device_id TEXT NOT NULL,
                requester_uid INTEGER NOT NULL CHECK (requester_uid >= 0),
                operation_key TEXT NOT NULL,
                input_digest BLOB NOT NULL CHECK (length(input_digest) = 32),
                package_name TEXT NOT NULL,
                generation INTEGER NOT NULL CHECK (generation >= 0),
                state TEXT NOT NULL CHECK (state IN (
                    'planning', 'pending', 'approved', 'executing', 'no_change', 'invalid',
                    'denied', 'expired', 'cancelled', 'stale', 'succeeded', 'failed', 'recovery_required'
                ))
            );
            CREATE UNIQUE INDEX IF NOT EXISTS requests_idempotency
                ON requests (requester_uid, operation_key);
            CREATE UNIQUE INDEX IF NOT EXISTS requests_one_active_per_device
                ON requests (device_id)
                WHERE state IN ({ACTIVE_STATES});
            CREATE TABLE IF NOT EXISTS request_events (
                request_id TEXT NOT NULL REFERENCES requests (request_id) ON DELETE RESTRICT,
                sequence INTEGER NOT NULL CHECK (sequence > 0),
                state TEXT NOT NULL,
                PRIMARY KEY (request_id, sequence)
            );
            "
        ))?;
        Ok(Self { connection, device_id: LOCAL_DEVICE_ID })
    }

    /// Inserts a policy-approved `planning` request or recovers an exact retry.
    pub fn submit(
        &mut self,
        request: SubmitPackageInstall,
        policy: &impl PackageInstallPolicy,
    ) -> Result<SubmitOutcome, BrokerError> {
        if policy.evaluate(request.requester_uid, &request.package_name) == PolicyDecision::Deny {
            return Err(BrokerError::PolicyDenied);
        }

        let transaction = self.connection.transaction_with_behavior(TransactionBehavior::Immediate)?;
        let digest = input_digest(&request.package_name);
        if let Some(existing) = lookup_idempotency(&transaction, request.requester_uid, &request.operation_key)? {
            if existing.input_digest == digest {
                transaction.commit()?;
                return Ok(SubmitOutcome::Existing(existing.summary));
            }
            return Err(BrokerError::IdempotencyConflict);
        }

        if let Some(request_id) = transaction
            .query_row(
                "SELECT request_id FROM requests WHERE device_id = ?1 AND state IN ('planning', 'pending', 'approved', 'executing') LIMIT 1",
                [self.device_id],
                |row| row.get::<_, String>(0),
            )
            .optional()?
        {
            return Err(BrokerError::Busy { request_id });
        }

        transaction.execute(
            "INSERT INTO requests (request_id, device_id, requester_uid, operation_key, input_digest, package_name, generation, state)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, 'planning')",
            params![
                request.request_id.as_str(),
                self.device_id,
                i64::from(request.requester_uid.as_u32()),
                request.operation_key.as_str(),
                digest.as_slice(),
                request.package_name.as_str(),
                i64::try_from(request.generation).map_err(|_| BrokerError::NumericOutOfRange)?,
            ],
        )?;
        transaction.execute(
            "INSERT INTO request_events (request_id, sequence, state) VALUES (?1, 1, 'planning')",
            [request.request_id.as_str()],
        )?;
        transaction.commit()?;
        Ok(SubmitOutcome::Created(RequestSummary {
            request_id: request.request_id,
            requester_uid: request.requester_uid,
            state: RequestState::Planning,
            generation: request.generation,
        }))
    }

    /// Applies one valid lifecycle compare-and-set transition and records its event.
    pub fn transition(
        &mut self,
        request_id: &PublicId,
        expected: RequestState,
        next: RequestState,
    ) -> Result<RequestState, BrokerError> {
        if !expected.permits(next) {
            return Err(BrokerError::InvalidTransition { from: expected, to: next });
        }
        let transaction = self.connection.transaction_with_behavior(TransactionBehavior::Immediate)?;
        let changed = transaction.execute(
            "UPDATE requests SET state = ?1 WHERE request_id = ?2 AND state = ?3",
            params![next.as_db(), request_id.as_str(), expected.as_db()],
        )?;
        if changed != 1 {
            let actual = request_state(&transaction, request_id)?;
            return match actual {
                Some(actual) => Err(BrokerError::LifecycleRaceLost { actual }),
                None => Err(BrokerError::NotFound),
            };
        }
        transaction.execute(
            "INSERT INTO request_events (request_id, sequence, state)
             SELECT request_id, COALESCE(MAX(sequence), 0) + 1, ?2
               FROM request_events
              WHERE request_id = ?1",
            params![request_id.as_str(), next.as_db()],
        )?;
        transaction.commit()?;
        Ok(next)
    }

    /// Reads a request summary for an already-authorized local caller.
    pub fn request(&self, request_id: &PublicId) -> Result<Option<RequestSummary>, BrokerError> {
        self.connection
            .query_row(
                "SELECT requester_uid, state, generation FROM requests WHERE request_id = ?1",
                [request_id.as_str()],
                |row| {
                    let uid = row.get::<_, i64>(0)?;
                    let state = row.get::<_, String>(1)?;
                    let generation = row.get::<_, i64>(2)?;
                    summary_from_values(request_id.clone(), uid, &state, generation)
                        .map_err(|error| rusqlite::Error::ToSqlConversionFailure(Box::new(error)))
                },
            )
            .optional()
            .map_err(BrokerError::from)
    }
}

struct IdempotencyRecord {
    input_digest: [u8; 32],
    summary: RequestSummary,
}

fn lookup_idempotency(
    transaction: &Transaction<'_>,
    requester_uid: RequesterUid,
    operation_key: &OperationKey,
) -> Result<Option<IdempotencyRecord>, BrokerError> {
    transaction
        .query_row(
            "SELECT request_id, input_digest, state, generation FROM requests WHERE requester_uid = ?1 AND operation_key = ?2",
            params![i64::from(requester_uid.as_u32()), operation_key.as_str()],
            |row| {
                let request_id = row.get::<_, String>(0)?;
                let digest = row.get::<_, Vec<u8>>(1)?;
                let state = row.get::<_, String>(2)?;
                let generation = row.get::<_, i64>(3)?;
                let input_digest: [u8; 32] = digest.try_into().map_err(|_| rusqlite::Error::InvalidQuery)?;
                let request_id = PublicId::parse(request_id).map_err(|_| rusqlite::Error::InvalidQuery)?;
                let summary = summary_from_values(request_id, i64::from(requester_uid.as_u32()), &state, generation)
                    .map_err(|error| rusqlite::Error::ToSqlConversionFailure(Box::new(error)))?;
                Ok(IdempotencyRecord { input_digest, summary })
            },
        )
        .optional()
        .map_err(BrokerError::from)
}

fn request_state(transaction: &Transaction<'_>, request_id: &PublicId) -> Result<Option<RequestState>, BrokerError> {
    transaction
        .query_row(
            "SELECT state FROM requests WHERE request_id = ?1",
            [request_id.as_str()],
            |row| row.get::<_, String>(0),
        )
        .optional()?
        .map_or(Ok(None), |state| RequestState::from_db(&state).map(Some))
}

fn summary_from_values(
    request_id: PublicId,
    requester_uid: i64,
    state: &str,
    generation: i64,
) -> Result<RequestSummary, BrokerError> {
    Ok(RequestSummary {
        request_id,
        requester_uid: RequesterUid(u32::try_from(requester_uid).map_err(|_| BrokerError::NumericOutOfRange)?),
        state: RequestState::from_db(state)?,
        generation: u64::try_from(generation).map_err(|_| BrokerError::NumericOutOfRange)?,
    })
}

fn input_digest(package_name: &PackageName) -> [u8; 32] {
    let mut hasher = Sha256::new();
    hasher.update(b"rootpermit/v1/package-install-input\0");
    hasher.update(package_name.as_str().as_bytes());
    hasher.finalize().into()
}

const fn is_base64url(byte: u8) -> bool {
    byte.is_ascii_alphanumeric() || matches!(byte, b'_' | b'-')
}

const fn is_package_character(byte: u8) -> bool {
    byte.is_ascii_lowercase() || byte.is_ascii_digit() || matches!(byte, b'+' | b'.' | b'-')
}

#[cfg(test)]
mod tests {
    use super::*;

    const REQUEST_A: &str = "AbCdEfGhIjKlMnOpQrStUw";
    const REQUEST_B: &str = "ZyXwVuTsRqPoNmLkJiHgFe";
    const KEY_A: &str = "aBcDeFgHiJkLmNoPqRsTuVwX";
    const KEY_B: &str = "zYxWvUtSrQpOnMlKjIhGfEdC";

    fn request(id: &str, uid: u32, key: &str, package: &str) -> SubmitPackageInstall {
        SubmitPackageInstall {
            request_id: PublicId::parse(id).unwrap(),
            requester_uid: RequesterUid::from_peer_cred(uid),
            operation_key: OperationKey::parse(key).unwrap(),
            package_name: PackageName::parse(package).unwrap(),
            generation: 3,
        }
    }

    fn allow(package: &str) -> PackageAllowlist {
        PackageAllowlist::new([PackageName::parse(package).unwrap()])
    }

    #[test]
    fn package_intake_rejects_versions_urls_paths_flags_and_architectures() {
        for invalid in [
            "f", "ffmpeg=7", "ffmpeg:amd64", "https://example.test/pkg", "./ffmpeg", "--assume-yes", "ffmpeg;id",
            "FFmpeg", "ff mpeg", "ffmpeg/../apt", "ffmpeg_1",
        ] {
            assert_eq!(PackageName::parse(invalid), Err(IntakeError::InvalidPackageName), "{invalid}");
        }
        assert_eq!(PackageName::parse("ffmpeg").unwrap().as_str(), "ffmpeg");
        assert_eq!(PackageName::parse("libvpx7").unwrap().as_str(), "libvpx7");
    }

    #[test]
    fn policy_denial_creates_no_request() {
        let mut store = BrokerStore::in_memory().unwrap();
        let denied = request(REQUEST_A, 1000, KEY_A, "ffmpeg");
        let error = store.submit(denied.clone(), &allow("curl")).unwrap_err();
        assert!(matches!(error, BrokerError::PolicyDenied));
        assert_eq!(store.request(&denied.request_id).unwrap(), None);
    }

    #[test]
    fn exact_uid_key_retry_recovers_original_but_changed_input_conflicts() {
        let mut store = BrokerStore::in_memory().unwrap();
        let policy = PackageAllowlist::new([
            PackageName::parse("ffmpeg").unwrap(),
            PackageName::parse("curl").unwrap(),
        ]);
        let initial = request(REQUEST_A, 1000, KEY_A, "ffmpeg");
        assert!(matches!(store.submit(initial.clone(), &policy).unwrap(), SubmitOutcome::Created(_)));

        let retry = request(REQUEST_B, 1000, KEY_A, "ffmpeg");
        assert_eq!(
            store.submit(retry, &policy).unwrap(),
            SubmitOutcome::Existing(RequestSummary {
                request_id: initial.request_id.clone(),
                requester_uid: initial.requester_uid,
                state: RequestState::Planning,
                generation: initial.generation,
            })
        );
        let changed = request(REQUEST_B, 1000, KEY_A, "curl");
        assert!(matches!(store.submit(changed, &policy), Err(BrokerError::IdempotencyConflict)));
    }

    #[test]
    fn active_slot_is_global_per_broker_and_releases_only_at_terminal_state() {
        let mut store = BrokerStore::in_memory().unwrap();
        let policy = PackageAllowlist::new([
            PackageName::parse("ffmpeg").unwrap(),
            PackageName::parse("curl").unwrap(),
        ]);
        let first = request(REQUEST_A, 1000, KEY_A, "ffmpeg");
        let second = request(REQUEST_B, 1001, KEY_B, "curl");
        store.submit(first.clone(), &policy).unwrap();
        assert!(matches!(store.submit(second.clone(), &policy), Err(BrokerError::Busy { .. })));
        store.transition(&first.request_id, RequestState::Planning, RequestState::NoChange).unwrap();
        assert!(matches!(store.submit(second, &policy).unwrap(), SubmitOutcome::Created(_)));
    }

    #[test]
    fn lifecycle_cas_and_terminal_edges_fail_closed() {
        let mut store = BrokerStore::in_memory().unwrap();
        let initial = request(REQUEST_A, 1000, KEY_A, "ffmpeg");
        store.submit(initial.clone(), &allow("ffmpeg")).unwrap();
        assert!(matches!(
            store.transition(&initial.request_id, RequestState::Pending, RequestState::Approved),
            Err(BrokerError::LifecycleRaceLost { actual: RequestState::Planning })
        ));
        assert!(matches!(
            store.transition(&initial.request_id, RequestState::Planning, RequestState::Executing),
            Err(BrokerError::InvalidTransition { .. })
        ));
        store.transition(&initial.request_id, RequestState::Planning, RequestState::Pending).unwrap();
        store.transition(&initial.request_id, RequestState::Pending, RequestState::Denied).unwrap();
        assert!(RequestState::Denied.is_terminal());
        assert!(!RequestState::Denied.permits(RequestState::Approved));
        assert!(matches!(
            store.transition(&initial.request_id, RequestState::Denied, RequestState::Approved),
            Err(BrokerError::InvalidTransition { .. })
        ));
    }

    #[test]
    fn all_documented_lifecycle_edges_are_accepted_and_undocumented_edges_rejected() {
        let accepted = [
            (RequestState::Planning, RequestState::Pending),
            (RequestState::Planning, RequestState::NoChange),
            (RequestState::Planning, RequestState::Invalid),
            (RequestState::Pending, RequestState::Approved),
            (RequestState::Pending, RequestState::Denied),
            (RequestState::Pending, RequestState::Expired),
            (RequestState::Pending, RequestState::Cancelled),
            (RequestState::Pending, RequestState::Stale),
            (RequestState::Approved, RequestState::Executing),
            (RequestState::Approved, RequestState::Cancelled),
            (RequestState::Approved, RequestState::Stale),
            (RequestState::Approved, RequestState::Expired),
            (RequestState::Executing, RequestState::Succeeded),
            (RequestState::Executing, RequestState::Failed),
            (RequestState::Executing, RequestState::RecoveryRequired),
            (RequestState::RecoveryRequired, RequestState::Succeeded),
            (RequestState::RecoveryRequired, RequestState::Failed),
        ];
        assert!(accepted.into_iter().all(|(from, to)| from.permits(to)));
        assert!(!RequestState::Planning.permits(RequestState::Succeeded));
        assert!(!RequestState::Approved.permits(RequestState::Denied));
        assert!(!RequestState::Succeeded.permits(RequestState::Failed));
    }
}
