//! Root-only, SQLite-backed lifecycle authority for the first RootPermit slice.
//!
//! This crate deliberately accepts only a typed Debian binary package name. It
//! owns the request/idempotency state transaction, but it does not plan or
//! execute APT work yet; those responsibilities belong to later M2/M4 layers.

#![forbid(unsafe_code)]

use rusqlite::{
    Connection, OptionalExtension, Transaction, TransactionBehavior, params,
};
use rp_protocol::{CborValue, Decision, Digest, Domain, digest_cbor};
use sha2::{Digest as _, Sha256};
use std::collections::{BTreeMap, BTreeSet};
use thiserror::Error;

const LOCAL_DEVICE_ID: &str = "AAAAAAAAAAAAAAAAAAAAAA";
const ACTIVE_STATES: &str = "'planning', 'pending', 'approved', 'executing'";

/// A kernel-authenticated requester UID.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct RequesterUid(u32);

impl RequesterUid {
    /// Creates a requester UID from the value supplied by `SO_PEERCRED`.
    #[must_use]
    pub const fn from_peer_cred(uid: u32) -> Self {
        Self(uid)
    }

    /// Returns the numeric Linux UID for persistence only.
    #[must_use]
    pub const fn as_u32(self) -> u32 {
        self.0
    }
}

/// A public RootPermit identifier: exactly 16 random bytes in base64url form.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct PublicId(String);

impl PublicId {
    /// Parses a public request identifier without accepting paths or control characters.
    pub fn parse(value: impl Into<String>) -> Result<Self, IntakeError> {
        let value = value.into();
        if value.len() != 22 || !value.bytes().all(is_base64url) {
            return Err(IntakeError::InvalidPublicId);
        }
        Ok(Self(value))
    }

    /// Returns the database-safe opaque identifier.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

/// Caller-selected key used to make a single package request idempotent.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct OperationKey(String);

impl OperationKey {
    /// Parses a bounded opaque operation key; it is never a shell fragment.
    pub fn parse(value: impl Into<String>) -> Result<Self, IntakeError> {
        let value = value.into();
        if !(16..=128).contains(&value.len()) || !value.bytes().all(is_base64url) {
            return Err(IntakeError::InvalidOperationKey);
        }
        Ok(Self(value))
    }

    /// Returns the opaque key for an equality-only database comparison.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

/// The only v1 agent-controlled operation input.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct PackageName(String);

impl PackageName {
    /// Parses a base Debian binary package name, excluding architecture, version and flags.
    pub fn parse(value: impl Into<String>) -> Result<Self, IntakeError> {
        let value = value.into();
        let bytes = value.as_bytes();
        if !(2..=64).contains(&bytes.len())
            || !bytes.first().is_some_and(u8::is_ascii_lowercase)
            || !bytes[1..].iter().copied().all(is_package_character)
        {
            return Err(IntakeError::InvalidPackageName);
        }
        Ok(Self(value))
    }

    /// Returns the validated package name.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

/// Errors raised before an agent request can influence broker state.
#[derive(Debug, Error, Clone, PartialEq, Eq)]
pub enum IntakeError {
    /// The request ID is not a 16-byte base64url identifier.
    #[error("request id must be a 16-byte base64url value")]
    InvalidPublicId,
    /// The caller did not supply a bounded opaque idempotency key.
    #[error("operation key must be a 16-128 character base64url value")]
    InvalidOperationKey,
    /// The package name is not a bounded, native Debian binary package name.
    #[error("package name must be 2-64 lowercase ASCII Debian-name characters")]
    InvalidPackageName,
}

/// A complete typed input to `package.install`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SubmitPackageInstall {
    /// Fresh public request ID generated by the broker, not the agent.
    pub request_id: PublicId,
    /// Caller identity supplied from `SO_PEERCRED`.
    pub requester_uid: RequesterUid,
    /// Caller retry key.
    pub operation_key: OperationKey,
    /// The sole agent-controlled operation value.
    pub package_name: PackageName,
    /// Credential generation captured when the request begins.
    pub generation: u64,
}

/// Policy decision for the one v1 operation type.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PolicyDecision {
    /// The validated package may enter planning.
    Allow,
    /// The package must not create any local request record.
    Deny,
}

/// Root-controlled policy consulted before a request becomes durable.
pub trait PackageInstallPolicy {
    /// Evaluates the package against the locally configured policy.
    fn evaluate(&self, requester_uid: RequesterUid, package_name: &PackageName) -> PolicyDecision;
}

/// Explicit package allowlist policy used by the local broker skeleton and tests.
#[derive(Debug, Clone, Default)]
pub struct PackageAllowlist {
    packages: BTreeSet<PackageName>,
}

impl PackageAllowlist {
    /// Builds an allowlist from already-validated package names.
    #[must_use]
    pub fn new(packages: impl IntoIterator<Item = PackageName>) -> Self {
        Self { packages: packages.into_iter().collect() }
    }
}

impl PackageInstallPolicy for PackageAllowlist {
    fn evaluate(&self, _requester_uid: RequesterUid, package_name: &PackageName) -> PolicyDecision {
        if self.packages.contains(package_name) {
            PolicyDecision::Allow
        } else {
            PolicyDecision::Deny
        }
    }
}

/// Authoritative lifecycle state retained in the broker database.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RequestState {
    /// A typed input has passed policy and awaits the planner.
    Planning,
    /// A frozen signed plan awaits a decision.
    Pending,
    /// A matching approval was accepted exactly once.
    Approved,
    /// The helper has received an execution authorization.
    Executing,
    /// Planning found no package transition.
    NoChange,
    /// Validation or planning rejected the request.
    Invalid,
    /// A matching deny assertion won the lifecycle race.
    Denied,
    /// The local monotonic deadline won the lifecycle race.
    Expired,
    /// The requester cancellation won before execution.
    Cancelled,
    /// The credential generation changed before execution.
    Stale,
    /// The helper proved the exact requested final state.
    Succeeded,
    /// The helper proved a failure without claiming rollback.
    Failed,
    /// A crash or ambiguity requires root reconciliation.
    RecoveryRequired,
}

impl RequestState {
    /// Returns whether this state closes the request and releases the active slot.
    #[must_use]
    pub const fn is_terminal(self) -> bool {
        matches!(
            self,
            Self::NoChange
                | Self::Invalid
                | Self::Denied
                | Self::Expired
                | Self::Cancelled
                | Self::Stale
                | Self::Succeeded
                | Self::Failed
        )
    }

    /// Returns whether a lifecycle edge is explicitly permitted by v2 section 5.2.
    #[must_use]
    pub const fn permits(self, next: Self) -> bool {
        matches!(
            (self, next),
            (Self::Planning, Self::Pending | Self::NoChange | Self::Invalid)
                | (Self::Pending, Self::Approved | Self::Denied | Self::Expired | Self::Cancelled | Self::Stale)
                | (Self::Approved, Self::Executing | Self::Cancelled | Self::Stale | Self::Expired)
                | (Self::Executing, Self::Succeeded | Self::Failed | Self::RecoveryRequired)
                | (Self::RecoveryRequired, Self::Succeeded | Self::Failed)
        )
    }

    const fn as_db(self) -> &'static str {
        match self {
            Self::Planning => "planning",
            Self::Pending => "pending",
            Self::Approved => "approved",
            Self::Executing => "executing",
            Self::NoChange => "no_change",
            Self::Invalid => "invalid",
            Self::Denied => "denied",
            Self::Expired => "expired",
            Self::Cancelled => "cancelled",
            Self::Stale => "stale",
            Self::Succeeded => "succeeded",
            Self::Failed => "failed",
            Self::RecoveryRequired => "recovery_required",
        }
    }

    fn from_db(value: &str) -> Result<Self, BrokerError> {
        match value {
            "planning" => Ok(Self::Planning),
            "pending" => Ok(Self::Pending),
            "approved" => Ok(Self::Approved),
            "executing" => Ok(Self::Executing),
            "no_change" => Ok(Self::NoChange),
            "invalid" => Ok(Self::Invalid),
            "denied" => Ok(Self::Denied),
            "expired" => Ok(Self::Expired),
            "cancelled" => Ok(Self::Cancelled),
            "stale" => Ok(Self::Stale),
            "succeeded" => Ok(Self::Succeeded),
            "failed" => Ok(Self::Failed),
            "recovery_required" => Ok(Self::RecoveryRequired),
            _ => Err(BrokerError::CorruptState),
        }
    }
}

/// A caller-safe projection of a local request.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RequestSummary {
    /// Opaque request ID.
    pub request_id: PublicId,
    /// Requester that owns the idempotency relationship.
    pub requester_uid: RequesterUid,
    /// Current durable lifecycle state.
    pub state: RequestState,
    /// The frozen credential generation boundary.
    pub generation: u64,
}

/// Result of a typed submission.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SubmitOutcome {
    /// A new request entered `planning`.
    Created(RequestSummary),
    /// The exact `(uid, operation key, input)` retry recovered its original request.
    Existing(RequestSummary),
}

/// Stable broker failures for lifecycle/state authority.
#[derive(Debug, Error)]
pub enum BrokerError {
    /// SQLite rejected or could not persist a state transition.
    #[error(transparent)]
    Sqlite(#[from] rusqlite::Error),
    /// The package policy rejected the request before any durable state was created.
    #[error("package install is not allowed by local policy")]
    PolicyDenied,
    /// The operation key was reused by one UID with different typed input.
    #[error("operation key was reused with different input")]
    IdempotencyConflict,
    /// A non-terminal request already consumes the one active device slot.
    #[error("a request is already active on this device: {request_id}")]
    Busy {
        /// Opaque request ID that owns the active slot.
        request_id: String,
    },
    /// The caller expected a state that did not win the compare-and-set race.
    #[error("lifecycle compare-and-set lost; current state is {actual:?}")]
    LifecycleRaceLost {
        /// The state observed after the failed CAS.
        actual: RequestState,
    },
    /// The requested edge is not in the v1 lifecycle graph.
    #[error("lifecycle transition from {from:?} to {to:?} is not permitted")]
    InvalidTransition {
        /// Expected source state.
        from: RequestState,
        /// Requested destination state.
        to: RequestState,
    },
    /// No local request exists for the opaque ID.
    #[error("request does not exist")]
    NotFound,
    /// Database data violates a broker-owned invariant.
    #[error("broker database contains an invalid lifecycle value")]
    CorruptState,
    /// SQLite stored an integer that does not fit its security-relevant type.
    #[error("broker database contains an out-of-range numeric value")]
    NumericOutOfRange,
}

/// Authoritative local state store; no other component may mutate its connection.
pub struct BrokerStore {
    connection: Connection,
    device_id: &'static str,
}

impl BrokerStore {
    /// Creates an in-memory store for deterministic lifecycle tests.
    pub fn in_memory() -> Result<Self, BrokerError> {
        let connection = Connection::open_in_memory()?;
        Self::from_connection(connection)
    }

    /// Installs broker-owned schema and pragmas on an otherwise private connection.
    pub fn from_connection(connection: Connection) -> Result<Self, BrokerError> {
        connection.execute_batch(&format!(
            "
            PRAGMA foreign_keys = ON;
            PRAGMA journal_mode = WAL;
            PRAGMA synchronous = FULL;
            CREATE TABLE IF NOT EXISTS requests (
                request_id TEXT PRIMARY KEY,
                device_id TEXT NOT NULL,
                requester_uid INTEGER NOT NULL CHECK (requester_uid >= 0),
                operation_key TEXT NOT NULL,
                input_digest BLOB NOT NULL CHECK (length(input_digest) = 32),
                package_name TEXT NOT NULL,
                generation INTEGER NOT NULL CHECK (generation >= 0),
                state TEXT NOT NULL CHECK (state IN (
                    'planning', 'pending', 'approved', 'executing', 'no_change', 'invalid',
                    'denied', 'expired', 'cancelled', 'stale', 'succeeded', 'failed', 'recovery_required'
                ))
            );
            CREATE UNIQUE INDEX IF NOT EXISTS requests_idempotency
                ON requests (requester_uid, operation_key);
            CREATE UNIQUE INDEX IF NOT EXISTS requests_one_active_per_device
                ON requests (device_id)
                WHERE state IN ({ACTIVE_STATES});
            CREATE TABLE IF NOT EXISTS request_events (
                request_id TEXT NOT NULL REFERENCES requests (request_id) ON DELETE RESTRICT,
                sequence INTEGER NOT NULL CHECK (sequence > 0),
                state TEXT NOT NULL,
                reason INTEGER NOT NULL CHECK (reason > 0),
                previous_event_digest BLOB CHECK (previous_event_digest IS NULL OR length(previous_event_digest) = 32),
                event_digest BLOB NOT NULL CHECK (length(event_digest) = 32),
                PRIMARY KEY (request_id, sequence)
            );
            "
        ))?;
        Ok(Self { connection, device_id: LOCAL_DEVICE_ID })
    }

    /// Inserts a policy-approved `planning` request or recovers an exact retry.
    pub fn submit(
        &mut self,
        request: SubmitPackageInstall,
        policy: &impl PackageInstallPolicy,
    ) -> Result<SubmitOutcome, BrokerError> {
        if policy.evaluate(request.requester_uid, &request.package_name) == PolicyDecision::Deny {
            return Err(BrokerError::PolicyDenied);
        }

        let transaction = self.connection.transaction_with_behavior(TransactionBehavior::Immediate)?;
        let digest = input_digest(&request.package_name);
        if let Some(existing) = lookup_idempotency(&transaction, request.requester_uid, &request.operation_key)? {
            if existing.input_digest == digest {
                transaction.commit()?;
                return Ok(SubmitOutcome::Existing(existing.summary));
            }
            return Err(BrokerError::IdempotencyConflict);
        }

        if let Some(request_id) = transaction
            .query_row(
                "SELECT request_id FROM requests WHERE device_id = ?1 AND state IN ('planning', 'pending', 'approved', 'executing') LIMIT 1",
                [self.device_id],
                |row| row.get::<_, String>(0),
            )
            .optional()?
        {
            return Err(BrokerError::Busy { request_id });
        }

        transaction.execute(
            "INSERT INTO requests (request_id, device_id, requester_uid, operation_key, input_digest, package_name, generation, state)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, 'planning')",
            params![
                request.request_id.as_str(),
                self.device_id,
                i64::from(request.requester_uid.as_u32()),
                request.operation_key.as_str(),
                digest.as_slice(),
                request.package_name.as_str(),
                i64::try_from(request.generation).map_err(|_| BrokerError::NumericOutOfRange)?,
            ],
        )?;
        let event_digest = lifecycle_event_digest(
            &request.request_id,
            1,
            None,
            RequestState::Planning,
            TransitionReason::Created,
        );
        transaction.execute(
            "INSERT INTO request_events (request_id, sequence, state, reason, previous_event_digest, event_digest)
             VALUES (?1, 1, 'planning', ?2, NULL, ?3)",
            params![request.request_id.as_str(), TransitionReason::Created.code(), event_digest.as_slice()],
        )?;
        transaction.commit()?;
        Ok(SubmitOutcome::Created(RequestSummary {
            request_id: request.request_id,
            requester_uid: request.requester_uid,
            state: RequestState::Planning,
            generation: request.generation,
        }))
    }

    /// Applies one valid lifecycle compare-and-set transition and records its event.
    pub fn transition(
        &mut self,
        request_id: &PublicId,
        expected: RequestState,
        next: RequestState,
    ) -> Result<RequestState, BrokerError> {
        if !expected.permits(next) {
            return Err(BrokerError::InvalidTransition { from: expected, to: next });
        }
        let transaction = self.connection.transaction_with_behavior(TransactionBehavior::Immediate)?;
        let changed = transaction.execute(
            "UPDATE requests SET state = ?1 WHERE request_id = ?2 AND state = ?3",
            params![next.as_db(), request_id.as_str(), expected.as_db()],
        )?;
        if changed != 1 {
            let actual = request_state(&transaction, request_id)?;
            return match actual {
                Some(actual) => Err(BrokerError::LifecycleRaceLost { actual }),
                None => Err(BrokerError::NotFound),
            };
        }
        let (sequence, previous_event_digest) = transaction.query_row(
            "SELECT sequence, event_digest FROM request_events WHERE request_id = ?1 ORDER BY sequence DESC LIMIT 1",
            [request_id.as_str()],
            |row| {
                let sequence = row.get::<_, i64>(0)?;
                let digest = row.get::<_, Vec<u8>>(1)?;
                Ok((sequence, digest))
            },
        )?;
        let sequence = u64::try_from(sequence).map_err(|_| BrokerError::NumericOutOfRange)?.saturating_add(1);
        let previous_event_digest: Digest = previous_event_digest
            .try_into()
            .map_err(|_| BrokerError::CorruptState)?;
        let reason = transition_reason(next);
        let event_digest = lifecycle_event_digest(request_id, sequence, Some(previous_event_digest), next, reason);
        transaction.execute(
            "INSERT INTO request_events (request_id, sequence, state, reason, previous_event_digest, event_digest)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6)",
            params![
                request_id.as_str(),
                i64::try_from(sequence).map_err(|_| BrokerError::NumericOutOfRange)?,
                next.as_db(),
                reason.code(),
                previous_event_digest.as_slice(),
                event_digest.as_slice(),
            ],
        )?;
        transaction.commit()?;
        Ok(next)
    }

    /// Reads a request summary for an already-authorized local caller.
    pub fn request(&self, request_id: &PublicId) -> Result<Option<RequestSummary>, BrokerError> {
        self.connection
            .query_row(
                "SELECT requester_uid, state, generation FROM requests WHERE request_id = ?1",
                [request_id.as_str()],
                |row| {
                    let uid = row.get::<_, i64>(0)?;
                    let state = row.get::<_, String>(1)?;
                    let generation = row.get::<_, i64>(2)?;
                    summary_from_values(request_id.clone(), uid, &state, generation)
                        .map_err(|error| rusqlite::Error::ToSqlConversionFailure(Box::new(error)))
                },
            )
            .optional()
            .map_err(BrokerError::from)
    }

    /// Reads the durable event chain for a request. This is intended for the
    /// future receipt/relay signer, not for a requester-facing RPC response.
    pub fn events(&self, request_id: &PublicId) -> Result<Vec<LifecycleEvent>, BrokerError> {
        let mut statement = self.connection.prepare(
            "SELECT sequence, state, reason, previous_event_digest, event_digest
             FROM request_events WHERE request_id = ?1 ORDER BY sequence ASC",
        )?;
        let rows = statement.query_map([request_id.as_str()], |row| {
            let sequence = row.get::<_, i64>(0)?;
            let state = row.get::<_, String>(1)?;
            let reason = row.get::<_, i64>(2)?;
            let previous = row.get::<_, Option<Vec<u8>>>(3)?;
            let digest = row.get::<_, Vec<u8>>(4)?;
            Ok((sequence, state, reason, previous, digest))
        })?;
        rows.map(|row| {
            let (sequence, state, reason, previous, digest) = row?;
            let previous_event_digest = previous
                .map(|value| value.try_into().map_err(|_| BrokerError::CorruptState))
                .transpose()?;
            let event_digest = digest.try_into().map_err(|_| BrokerError::CorruptState)?;
            Ok(LifecycleEvent {
                sequence: u64::try_from(sequence).map_err(|_| BrokerError::NumericOutOfRange)?,
                previous_event_digest,
                state: RequestState::from_db(&state)?,
                reason: transition_reason_from_code(reason)?,
                event_digest,
            })
        }).collect()
    }
}

struct IdempotencyRecord {
    input_digest: [u8; 32],
    summary: RequestSummary,
}

fn lookup_idempotency(
    transaction: &Transaction<'_>,
    requester_uid: RequesterUid,
    operation_key: &OperationKey,
) -> Result<Option<IdempotencyRecord>, BrokerError> {
    transaction
        .query_row(
            "SELECT request_id, input_digest, state, generation FROM requests WHERE requester_uid = ?1 AND operation_key = ?2",
            params![i64::from(requester_uid.as_u32()), operation_key.as_str()],
            |row| {
                let request_id = row.get::<_, String>(0)?;
                let digest = row.get::<_, Vec<u8>>(1)?;
                let state = row.get::<_, String>(2)?;
                let generation = row.get::<_, i64>(3)?;
                let input_digest: [u8; 32] = digest.try_into().map_err(|_| rusqlite::Error::InvalidQuery)?;
                let request_id = PublicId::parse(request_id).map_err(|_| rusqlite::Error::InvalidQuery)?;
                let summary = summary_from_values(request_id, i64::from(requester_uid.as_u32()), &state, generation)
                    .map_err(|error| rusqlite::Error::ToSqlConversionFailure(Box::new(error)))?;
                Ok(IdempotencyRecord { input_digest, summary })
            },
        )
        .optional()
        .map_err(BrokerError::from)
}

fn request_state(transaction: &Transaction<'_>, request_id: &PublicId) -> Result<Option<RequestState>, BrokerError> {
    transaction
        .query_row(
            "SELECT state FROM requests WHERE request_id = ?1",
            [request_id.as_str()],
            |row| row.get::<_, String>(0),
        )
        .optional()?
        .map_or(Ok(None), |state| RequestState::from_db(&state).map(Some))
}

fn summary_from_values(
    request_id: PublicId,
    requester_uid: i64,
    state: &str,
    generation: i64,
) -> Result<RequestSummary, BrokerError> {
    Ok(RequestSummary {
        request_id,
        requester_uid: RequesterUid(u32::try_from(requester_uid).map_err(|_| BrokerError::NumericOutOfRange)?),
        state: RequestState::from_db(state)?,
        generation: u64::try_from(generation).map_err(|_| BrokerError::NumericOutOfRange)?,
    })
}

fn input_digest(package_name: &PackageName) -> [u8; 32] {
    let mut hasher = Sha256::new();
    hasher.update(b"rootpermit/v1/package-install-input\0");
    hasher.update(package_name.as_str().as_bytes());
    hasher.finalize().into()
}

const fn is_base64url(byte: u8) -> bool {
    byte.is_ascii_alphanumeric() || matches!(byte, b'_' | b'-')
}

const fn is_package_character(byte: u8) -> bool {
    byte.is_ascii_lowercase() || byte.is_ascii_digit() || matches!(byte, b'+' | b'.' | b'-')
}

/// Result produced by the planner before a request can be presented for approval.
///
/// The real APT adapter is deliberately not represented here.  It belongs behind
/// the M4 helper boundary.  This type gives M2 a deterministic, testable seam
/// without letting a caller supply a plan, version, archive, or APT option.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum PlanOutcome {
    /// A frozen transition that is safe to bind into a pending request.
    Pending(FrozenPlan),
    /// The requested package is already in the desired state.
    NoChange { reason_code: u16 },
    /// Planning rejected the typed request without invoking a helper.
    Invalid { reason_code: u16 },
}

/// Minimal immutable projection of a frozen plan available before the APT
/// helper exists.  `manifest_digest` is supplied only by a trusted planner.
/// The complete v1 `PlanManifest` / `FrozenPlan` schema remains a protocol-crate
/// gap and must replace this projection before real execution is enabled.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FrozenPlan {
    pub package_name: PackageName,
    pub manifest_digest: Digest,
    pub plan_digest: Digest,
    pub action_count: u32,
}

impl FrozenPlan {
    /// Constructs a deterministic fake-plan projection for M2 tests.
    pub fn fake(package_name: PackageName, manifest_digest: Digest, action_count: u32) -> Result<Self, PlannerError> {
        let view = CborValue::Map(vec![
            (CborValue::Unsigned(1), CborValue::Text(package_name.as_str().to_owned())),
            (CborValue::Unsigned(2), CborValue::Bytes(manifest_digest.to_vec())),
            (CborValue::Unsigned(3), CborValue::Unsigned(u64::from(action_count))),
        ]);
        let plan_digest = digest_cbor(Domain::AptPlan, &view).map_err(|_| PlannerError::Canonicalization)?;
        Ok(Self { package_name, manifest_digest, plan_digest, action_count })
    }
}

/// Trusted planner seam. Implementations receive only a validated base package
/// name and cannot recover any discarded agent arguments.
pub trait Planner {
    fn plan(&self, package_name: &PackageName) -> Result<PlanOutcome, PlannerError>;
}

/// Planner failures are deliberately opaque to the requester-facing API.
#[derive(Debug, Error, Clone, PartialEq, Eq)]
pub enum PlannerError {
    #[error("planner could not produce a deterministic canonical plan")]
    Canonicalization,
    #[error("planner is temporarily unavailable")]
    Unavailable,
}

/// Deterministic planner used by M2 lifecycle tests. It cannot execute APT,
/// inspect the host, or manufacture an arbitrary package transition.
#[derive(Debug, Clone, Default)]
pub struct FakePlanner {
    outcomes: BTreeMap<PackageName, PlanOutcome>,
}

impl FakePlanner {
    #[must_use]
    pub fn with_outcomes(outcomes: impl IntoIterator<Item = (PackageName, PlanOutcome)>) -> Self {
        Self { outcomes: outcomes.into_iter().collect() }
    }
}

impl Planner for FakePlanner {
    fn plan(&self, package_name: &PackageName) -> Result<PlanOutcome, PlannerError> {
        Ok(self
            .outcomes
            .get(package_name)
            .cloned()
            .unwrap_or(PlanOutcome::Invalid { reason_code: 1 }))
    }
}

/// Reason recorded with a local state transition. Values are stable local audit
/// codes, not a replacement for the still-unimplemented v1 protocol event map.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TransitionReason {
    Created,
    PlannerPending,
    PlannerNoChange,
    PlannerInvalid,
    Approved,
    Denied,
    Expired,
    Cancelled,
    GenerationStale,
    ExecutionStarted,
    ExecutionSucceeded,
    ExecutionFailed,
    RecoveryRequired,
    ReconciledSucceeded,
    ReconciledFailed,
}

impl TransitionReason {
    const fn code(self) -> u64 {
        match self {
            Self::Created => 1,
            Self::PlannerPending => 2,
            Self::PlannerNoChange => 3,
            Self::PlannerInvalid => 4,
            Self::Approved => 5,
            Self::Denied => 6,
            Self::Expired => 7,
            Self::Cancelled => 8,
            Self::GenerationStale => 9,
            Self::ExecutionStarted => 10,
            Self::ExecutionSucceeded => 11,
            Self::ExecutionFailed => 12,
            Self::RecoveryRequired => 13,
            Self::ReconciledSucceeded => 14,
            Self::ReconciledFailed => 15,
        }
    }
}

fn transition_reason(state: RequestState) -> TransitionReason {
    match state {
        RequestState::Planning => TransitionReason::Created,
        RequestState::Pending => TransitionReason::PlannerPending,
        RequestState::NoChange => TransitionReason::PlannerNoChange,
        RequestState::Invalid => TransitionReason::PlannerInvalid,
        RequestState::Approved => TransitionReason::Approved,
        RequestState::Denied => TransitionReason::Denied,
        RequestState::Expired => TransitionReason::Expired,
        RequestState::Cancelled => TransitionReason::Cancelled,
        RequestState::Stale => TransitionReason::GenerationStale,
        RequestState::Executing => TransitionReason::ExecutionStarted,
        RequestState::Succeeded => TransitionReason::ExecutionSucceeded,
        RequestState::Failed => TransitionReason::ExecutionFailed,
        RequestState::RecoveryRequired => TransitionReason::RecoveryRequired,
    }
}

fn transition_reason_from_code(value: i64) -> Result<TransitionReason, BrokerError> {
    match value {
        1 => Ok(TransitionReason::Created),
        2 => Ok(TransitionReason::PlannerPending),
        3 => Ok(TransitionReason::PlannerNoChange),
        4 => Ok(TransitionReason::PlannerInvalid),
        5 => Ok(TransitionReason::Approved),
        6 => Ok(TransitionReason::Denied),
        7 => Ok(TransitionReason::Expired),
        8 => Ok(TransitionReason::Cancelled),
        9 => Ok(TransitionReason::GenerationStale),
        10 => Ok(TransitionReason::ExecutionStarted),
        11 => Ok(TransitionReason::ExecutionSucceeded),
        12 => Ok(TransitionReason::ExecutionFailed),
        13 => Ok(TransitionReason::RecoveryRequired),
        14 => Ok(TransitionReason::ReconciledSucceeded),
        15 => Ok(TransitionReason::ReconciledFailed),
        _ => Err(BrokerError::CorruptState),
    }
}

/// Append-only local lifecycle event with a deterministic hash-chain link.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LifecycleEvent {
    pub sequence: u64,
    pub previous_event_digest: Option<Digest>,
    pub state: RequestState,
    pub reason: TransitionReason,
    pub event_digest: Digest,
}

/// Unsigned receipt content prepared by M2. A broker signature cannot be added
/// yet because `rp-protocol` has no public COSE or Receipt schema interface.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ReceiptDraft {
    pub receipt_id: PublicId,
    pub request_id: PublicId,
    pub request_digest: Digest,
    pub plan_digest: Option<Digest>,
    pub terminal_state: RequestState,
    pub final_event_digest: Digest,
    pub receipt_digest: Digest,
}

/// A verifier is the only route by which an assertion reaches M2. The WebAuthn
/// parser/verifier is intentionally outside this crate; an unverified decision
/// must never be represented by this type.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct VerifiedDecision {
    pub request_digest: Digest,
    pub generation: u64,
    pub decision: Decision,
    pub assertion_digest: Digest,
}

/// Deterministic lifecycle authority used by the broker transaction layer.
/// Calls are intentionally serialized by `BrokerStore`'s `BEGIN IMMEDIATE`
/// transaction in a production adapter; this value object makes every race
/// winner and event-chain result independently testable.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LifecycleRecord {
    pub request_id: PublicId,
    pub receipt_id: PublicId,
    pub requested_package: PackageName,
    pub request_digest: Digest,
    pub generation: u64,
    pub deadline_mono_ns: u64,
    pub state: RequestState,
    pub plan: Option<FrozenPlan>,
    pub events: Vec<LifecycleEvent>,
    pub receipt: Option<ReceiptDraft>,
}

#[derive(Debug, Error, Clone, PartialEq, Eq)]
pub enum LifecycleError {
    #[error("lifecycle action is not allowed from {state:?}")]
    InvalidState { state: RequestState },
    #[error("verified decision does not bind this request")]
    DecisionContextMismatch,
    #[error("verified decision was made for stale credential generation")]
    DecisionGenerationStale,
    #[error("a terminal state already won the lifecycle race")]
    AlreadyTerminal,
    #[error("receipt is available only after a terminal state")]
    ReceiptNotReady,
    #[error("planner result does not bind the requested package")]
    PlannerPackageMismatch,
}

impl LifecycleRecord {
    /// Creates the durable in-memory representation immediately after typed
    /// input was accepted. Both IDs are broker-generated opaque identifiers.
    #[must_use]
    pub fn new(
        request_id: PublicId,
        receipt_id: PublicId,
        requested_package: PackageName,
        request_digest: Digest,
        generation: u64,
        deadline_mono_ns: u64,
    ) -> Self {
        let mut record = Self {
            request_id,
            receipt_id,
            requested_package,
            request_digest,
            generation,
            deadline_mono_ns,
            state: RequestState::Planning,
            plan: None,
            events: Vec::new(),
            receipt: None,
        };
        record.append(RequestState::Planning, TransitionReason::Created);
        record
    }

    /// Applies a trusted planner output. No decision or execution can happen
    /// while the record remains in `planning`.
    pub fn apply_plan(&mut self, outcome: PlanOutcome) -> Result<RequestState, LifecycleError> {
        if self.state != RequestState::Planning {
            return Err(self.state_error());
        }
        match outcome {
            PlanOutcome::Pending(plan) => {
                if plan.package_name != self.requested_package {
                    return Err(LifecycleError::PlannerPackageMismatch);
                }
                self.plan = Some(plan);
                self.winner(RequestState::Pending, TransitionReason::PlannerPending);
            }
            PlanOutcome::NoChange { .. } => self.winner(RequestState::NoChange, TransitionReason::PlannerNoChange),
            PlanOutcome::Invalid { .. } => self.winner(RequestState::Invalid, TransitionReason::PlannerInvalid),
        }
        Ok(self.state)
    }

    /// Accepts exactly one already-verified, context-bound decision. Expiry and
    /// generation changes are checked before the decision so their durable
    /// terminal transition wins deterministically.
    pub fn apply_verified_decision(
        &mut self,
        now_mono_ns: u64,
        active_generation: u64,
        decision: &VerifiedDecision,
    ) -> Result<RequestState, LifecycleError> {
        self.pre_execution_guard(now_mono_ns, active_generation)?;
        if self.state != RequestState::Pending {
            return Err(self.state_error());
        }
        if decision.request_digest != self.request_digest {
            return Err(LifecycleError::DecisionContextMismatch);
        }
        if decision.generation != self.generation {
            return Err(LifecycleError::DecisionGenerationStale);
        }
        match decision.decision {
            Decision::Approve => self.winner(RequestState::Approved, TransitionReason::Approved),
            Decision::Deny => self.winner(RequestState::Denied, TransitionReason::Denied),
        }
        Ok(self.state)
    }

    /// Cancels only before execution. A cancelled request cannot later be
    /// approved or handed to the helper.
    pub fn cancel(&mut self, now_mono_ns: u64, active_generation: u64) -> Result<RequestState, LifecycleError> {
        self.pre_execution_guard(now_mono_ns, active_generation)?;
        if !matches!(self.state, RequestState::Pending | RequestState::Approved) {
            return Err(self.state_error());
        }
        self.winner(RequestState::Cancelled, TransitionReason::Cancelled);
        Ok(self.state)
    }

    /// The sole authorization-to-execution transition. A generation change or
    /// expiry always wins before this can reach the helper boundary.
    pub fn begin_execution(&mut self, now_mono_ns: u64, active_generation: u64) -> Result<RequestState, LifecycleError> {
        self.pre_execution_guard(now_mono_ns, active_generation)?;
        if self.state != RequestState::Approved {
            return Err(self.state_error());
        }
        self.winner(RequestState::Executing, TransitionReason::ExecutionStarted);
        Ok(self.state)
    }

    /// Records a helper-proved outcome. It intentionally has no retry path.
    pub fn finish_execution(&mut self, succeeded: bool, recovery_required: bool) -> Result<RequestState, LifecycleError> {
        if self.state != RequestState::Executing {
            return Err(self.state_error());
        }
        match (succeeded, recovery_required) {
            (true, false) => self.winner(RequestState::Succeeded, TransitionReason::ExecutionSucceeded),
            (false, false) => self.winner(RequestState::Failed, TransitionReason::ExecutionFailed),
            (false, true) => self.winner(RequestState::RecoveryRequired, TransitionReason::RecoveryRequired),
            (true, true) => return Err(LifecycleError::InvalidState { state: self.state }),
        }
        Ok(self.state)
    }

    /// Root-only reconciliation has to prove either result; this method models
    /// only the state-machine edge and deliberately cannot restart execution.
    pub fn reconcile(&mut self, succeeded: bool) -> Result<RequestState, LifecycleError> {
        if self.state != RequestState::RecoveryRequired {
            return Err(self.state_error());
        }
        if succeeded {
            self.winner(RequestState::Succeeded, TransitionReason::ReconciledSucceeded);
        } else {
            self.winner(RequestState::Failed, TransitionReason::ReconciledFailed);
        }
        Ok(self.state)
    }

    fn pre_execution_guard(&mut self, now_mono_ns: u64, active_generation: u64) -> Result<(), LifecycleError> {
        if self.state.is_terminal() {
            return Err(LifecycleError::AlreadyTerminal);
        }
        if matches!(self.state, RequestState::Pending | RequestState::Approved) && now_mono_ns >= self.deadline_mono_ns {
            self.winner(RequestState::Expired, TransitionReason::Expired);
            return Err(LifecycleError::AlreadyTerminal);
        }
        if matches!(self.state, RequestState::Pending | RequestState::Approved) && active_generation != self.generation {
            self.winner(RequestState::Stale, TransitionReason::GenerationStale);
            return Err(LifecycleError::AlreadyTerminal);
        }
        Ok(())
    }

    fn state_error(&self) -> LifecycleError {
        if self.state.is_terminal() { LifecycleError::AlreadyTerminal } else { LifecycleError::InvalidState { state: self.state } }
    }

    fn winner(&mut self, next: RequestState, reason: TransitionReason) {
        debug_assert!(self.state.permits(next));
        self.state = next;
        self.append(next, reason);
        if next.is_terminal() {
            self.receipt = Some(self.make_receipt());
        }
    }

    fn append(&mut self, state: RequestState, reason: TransitionReason) {
        let sequence = u64::try_from(self.events.len()).unwrap_or(u64::MAX).saturating_add(1);
        let previous_event_digest = self.events.last().map(|event| event.event_digest);
        let event_digest = lifecycle_event_digest(&self.request_id, sequence, previous_event_digest, state, reason);
        self.events.push(LifecycleEvent { sequence, previous_event_digest, state, reason, event_digest });
    }

    fn make_receipt(&self) -> ReceiptDraft {
        let final_event_digest = self.events.last().map_or([0; 32], |event| event.event_digest);
        let plan_digest = self.plan.as_ref().and_then(|plan| (plan.plan_digest != [0; 32]).then_some(plan.plan_digest));
        let receipt_digest = receipt_digest(
            &self.receipt_id,
            &self.request_id,
            self.request_digest,
            plan_digest,
            self.state,
            final_event_digest,
        );
        ReceiptDraft {
            receipt_id: self.receipt_id.clone(),
            request_id: self.request_id.clone(),
            request_digest: self.request_digest,
            plan_digest,
            terminal_state: self.state,
            final_event_digest,
            receipt_digest,
        }
    }
}

fn lifecycle_event_digest(
    request_id: &PublicId,
    sequence: u64,
    previous_event_digest: Option<Digest>,
    state: RequestState,
    reason: TransitionReason,
) -> Digest {
    let mut hasher = Sha256::new();
    hasher.update(b"rootpermit/v1/local-lifecycle-event\0");
    hasher.update(request_id.as_str().as_bytes());
    hasher.update(sequence.to_be_bytes());
    hasher.update(previous_event_digest.unwrap_or([0; 32]));
    hasher.update(state.as_db().as_bytes());
    hasher.update(reason.code().to_be_bytes());
    hasher.finalize().into()
}

fn receipt_digest(
    receipt_id: &PublicId,
    request_id: &PublicId,
    request_digest: Digest,
    plan_digest: Option<Digest>,
    state: RequestState,
    final_event_digest: Digest,
) -> Digest {
    let mut hasher = Sha256::new();
    hasher.update(b"rootpermit/v1/local-receipt-draft\0");
    hasher.update(receipt_id.as_str().as_bytes());
    hasher.update(request_id.as_str().as_bytes());
    hasher.update(request_digest);
    hasher.update(plan_digest.unwrap_or([0; 32]));
    hasher.update(state.as_db().as_bytes());
    hasher.update(final_event_digest);
    hasher.finalize().into()
}

#[cfg(test)]
mod tests {
    use super::*;

    const REQUEST_A: &str = "AbCdEfGhIjKlMnOpQrStUw";
    const REQUEST_B: &str = "ZyXwVuTsRqPoNmLkJiHgFe";
    const KEY_A: &str = "aBcDeFgHiJkLmNoPqRsTuVwX";
    const KEY_B: &str = "zYxWvUtSrQpOnMlKjIhGfEdC";

    fn request(id: &str, uid: u32, key: &str, package: &str) -> SubmitPackageInstall {
        SubmitPackageInstall {
            request_id: PublicId::parse(id).unwrap(),
            requester_uid: RequesterUid::from_peer_cred(uid),
            operation_key: OperationKey::parse(key).unwrap(),
            package_name: PackageName::parse(package).unwrap(),
            generation: 3,
        }
    }

    fn allow(package: &str) -> PackageAllowlist {
        PackageAllowlist::new([PackageName::parse(package).unwrap()])
    }

    #[test]
    fn package_intake_rejects_versions_urls_paths_flags_and_architectures() {
        for invalid in [
            "f", "ffmpeg=7", "ffmpeg:amd64", "https://example.test/pkg", "./ffmpeg", "--assume-yes", "ffmpeg;id",
            "FFmpeg", "ff mpeg", "ffmpeg/../apt", "ffmpeg_1",
        ] {
            assert_eq!(PackageName::parse(invalid), Err(IntakeError::InvalidPackageName), "{invalid}");
        }
        assert_eq!(PackageName::parse("ffmpeg").unwrap().as_str(), "ffmpeg");
        assert_eq!(PackageName::parse("libvpx7").unwrap().as_str(), "libvpx7");
    }

    #[test]
    fn policy_denial_creates_no_request() {
        let mut store = BrokerStore::in_memory().unwrap();
        let denied = request(REQUEST_A, 1000, KEY_A, "ffmpeg");
        let error = store.submit(denied.clone(), &allow("curl")).unwrap_err();
        assert!(matches!(error, BrokerError::PolicyDenied));
        assert_eq!(store.request(&denied.request_id).unwrap(), None);
    }

    #[test]
    fn exact_uid_key_retry_recovers_original_but_changed_input_conflicts() {
        let mut store = BrokerStore::in_memory().unwrap();
        let policy = PackageAllowlist::new([
            PackageName::parse("ffmpeg").unwrap(),
            PackageName::parse("curl").unwrap(),
        ]);
        let initial = request(REQUEST_A, 1000, KEY_A, "ffmpeg");
        assert!(matches!(store.submit(initial.clone(), &policy).unwrap(), SubmitOutcome::Created(_)));

        let retry = request(REQUEST_B, 1000, KEY_A, "ffmpeg");
        assert_eq!(
            store.submit(retry, &policy).unwrap(),
            SubmitOutcome::Existing(RequestSummary {
                request_id: initial.request_id.clone(),
                requester_uid: initial.requester_uid,
                state: RequestState::Planning,
                generation: initial.generation,
            })
        );
        let changed = request(REQUEST_B, 1000, KEY_A, "curl");
        assert!(matches!(store.submit(changed, &policy), Err(BrokerError::IdempotencyConflict)));
    }

    #[test]
    fn active_slot_is_global_per_broker_and_releases_only_at_terminal_state() {
        let mut store = BrokerStore::in_memory().unwrap();
        let policy = PackageAllowlist::new([
            PackageName::parse("ffmpeg").unwrap(),
            PackageName::parse("curl").unwrap(),
        ]);
        let first = request(REQUEST_A, 1000, KEY_A, "ffmpeg");
        let second = request(REQUEST_B, 1001, KEY_B, "curl");
        store.submit(first.clone(), &policy).unwrap();
        assert!(matches!(store.submit(second.clone(), &policy), Err(BrokerError::Busy { .. })));
        store.transition(&first.request_id, RequestState::Planning, RequestState::NoChange).unwrap();
        assert!(matches!(store.submit(second, &policy).unwrap(), SubmitOutcome::Created(_)));
    }

    #[test]
    fn lifecycle_cas_and_terminal_edges_fail_closed() {
        let mut store = BrokerStore::in_memory().unwrap();
        let initial = request(REQUEST_A, 1000, KEY_A, "ffmpeg");
        store.submit(initial.clone(), &allow("ffmpeg")).unwrap();
        assert!(matches!(
            store.transition(&initial.request_id, RequestState::Pending, RequestState::Approved),
            Err(BrokerError::LifecycleRaceLost { actual: RequestState::Planning })
        ));
        assert!(matches!(
            store.transition(&initial.request_id, RequestState::Planning, RequestState::Executing),
            Err(BrokerError::InvalidTransition { .. })
        ));
        store.transition(&initial.request_id, RequestState::Planning, RequestState::Pending).unwrap();
        store.transition(&initial.request_id, RequestState::Pending, RequestState::Denied).unwrap();
        assert!(RequestState::Denied.is_terminal());
        assert!(!RequestState::Denied.permits(RequestState::Approved));
        assert!(matches!(
            store.transition(&initial.request_id, RequestState::Denied, RequestState::Approved),
            Err(BrokerError::InvalidTransition { .. })
        ));
    }

    #[test]
    fn sqlite_transition_persists_a_contiguous_hash_chain_in_the_same_transaction() {
        let mut store = BrokerStore::in_memory().unwrap();
        let initial = request(REQUEST_A, 1000, KEY_A, "ffmpeg");
        store.submit(initial.clone(), &allow("ffmpeg")).unwrap();
        store.transition(&initial.request_id, RequestState::Planning, RequestState::Pending).unwrap();
        store.transition(&initial.request_id, RequestState::Pending, RequestState::Denied).unwrap();
        let events = store.events(&initial.request_id).unwrap();
        assert_eq!(events.len(), 3);
        assert_eq!(events[0].sequence, 1);
        assert_eq!(events[0].previous_event_digest, None);
        assert_eq!(events[1].previous_event_digest, Some(events[0].event_digest));
        assert_eq!(events[2].previous_event_digest, Some(events[1].event_digest));
        assert_eq!(events[2].reason, TransitionReason::Denied);
    }

    #[test]
    fn all_documented_lifecycle_edges_are_accepted_and_undocumented_edges_rejected() {
        let accepted = [
            (RequestState::Planning, RequestState::Pending),
            (RequestState::Planning, RequestState::NoChange),
            (RequestState::Planning, RequestState::Invalid),
            (RequestState::Pending, RequestState::Approved),
            (RequestState::Pending, RequestState::Denied),
            (RequestState::Pending, RequestState::Expired),
            (RequestState::Pending, RequestState::Cancelled),
            (RequestState::Pending, RequestState::Stale),
            (RequestState::Approved, RequestState::Executing),
            (RequestState::Approved, RequestState::Cancelled),
            (RequestState::Approved, RequestState::Stale),
            (RequestState::Approved, RequestState::Expired),
            (RequestState::Executing, RequestState::Succeeded),
            (RequestState::Executing, RequestState::Failed),
            (RequestState::Executing, RequestState::RecoveryRequired),
            (RequestState::RecoveryRequired, RequestState::Succeeded),
            (RequestState::RecoveryRequired, RequestState::Failed),
        ];
        assert!(accepted.into_iter().all(|(from, to)| from.permits(to)));
        assert!(!RequestState::Planning.permits(RequestState::Succeeded));
        assert!(!RequestState::Approved.permits(RequestState::Denied));
        assert!(!RequestState::Succeeded.permits(RequestState::Failed));
    }

    fn lifecycle() -> LifecycleRecord {
        LifecycleRecord::new(
            PublicId::parse(REQUEST_A).unwrap(),
            PublicId::parse(REQUEST_B).unwrap(),
            PackageName::parse("ffmpeg").unwrap(),
            [9; 32],
            3,
            100,
        )
    }

    fn pending_plan() -> FrozenPlan {
        FrozenPlan::fake(PackageName::parse("ffmpeg").unwrap(), [7; 32], 2).unwrap()
    }

    #[test]
    fn fake_planner_is_deterministic_and_cannot_change_the_requested_package() {
        let plan = pending_plan();
        let planner = FakePlanner::with_outcomes([(PackageName::parse("ffmpeg").unwrap(), PlanOutcome::Pending(plan.clone()))]);
        assert_eq!(planner.plan(&PackageName::parse("ffmpeg").unwrap()).unwrap(), PlanOutcome::Pending(plan));
        assert_eq!(
            planner.plan(&PackageName::parse("curl").unwrap()).unwrap(),
            PlanOutcome::Invalid { reason_code: 1 }
        );

        let mut record = lifecycle();
        let changed = FrozenPlan::fake(PackageName::parse("curl").unwrap(), [7; 32], 1).unwrap();
        assert_eq!(record.apply_plan(PlanOutcome::Pending(changed)), Err(LifecycleError::PlannerPackageMismatch));
        assert_eq!(record.state, RequestState::Planning);
    }

    #[test]
    fn decision_expiry_cancel_and_generation_have_one_durable_winner() {
        let mut approved = lifecycle();
        approved.apply_plan(PlanOutcome::Pending(pending_plan())).unwrap();
        let proof = VerifiedDecision {
            request_digest: [9; 32], generation: 3, decision: Decision::Approve, assertion_digest: [4; 32],
        };
        assert_eq!(approved.apply_verified_decision(99, 3, &proof).unwrap(), RequestState::Approved);
        assert_eq!(approved.begin_execution(99, 4), Err(LifecycleError::AlreadyTerminal));
        assert_eq!(approved.state, RequestState::Stale);
        assert_eq!(approved.cancel(99, 3), Err(LifecycleError::AlreadyTerminal));

        let mut expired = lifecycle();
        expired.apply_plan(PlanOutcome::Pending(pending_plan())).unwrap();
        assert_eq!(expired.cancel(100, 3), Err(LifecycleError::AlreadyTerminal));
        assert_eq!(expired.state, RequestState::Expired);

        let mut denied = lifecycle();
        denied.apply_plan(PlanOutcome::Pending(pending_plan())).unwrap();
        let deny = VerifiedDecision {
            request_digest: [9; 32], generation: 3, decision: Decision::Deny, assertion_digest: [5; 32],
        };
        assert_eq!(denied.apply_verified_decision(99, 3, &deny).unwrap(), RequestState::Denied);
        assert_eq!(denied.apply_verified_decision(99, 3, &proof), Err(LifecycleError::AlreadyTerminal));
    }

    #[test]
    fn terminal_receipt_draft_commits_to_the_event_chain_without_claiming_a_signature() {
        let mut record = lifecycle();
        record.apply_plan(PlanOutcome::Pending(pending_plan())).unwrap();
        let proof = VerifiedDecision {
            request_digest: [9; 32], generation: 3, decision: Decision::Approve, assertion_digest: [4; 32],
        };
        record.apply_verified_decision(99, 3, &proof).unwrap();
        record.begin_execution(99, 3).unwrap();
        record.finish_execution(false, true).unwrap();
        assert_eq!(record.receipt, None);
        record.reconcile(false).unwrap();
        let receipt = record.receipt.clone().unwrap();
        assert_eq!(receipt.terminal_state, RequestState::Failed);
        assert_eq!(receipt.plan_digest, Some(pending_plan().plan_digest));
        assert_eq!(receipt.final_event_digest, record.events.last().unwrap().event_digest);
        assert!(record.events.windows(2).all(|events| events[1].previous_event_digest == Some(events[0].event_digest)));
        assert_ne!(receipt.receipt_digest, [0; 32]);
    }
}
